"use client";

import {useEffect,useMemo,useRef,useState} from "react";
import Link from "next/link";
import {createClient} from "@/lib/supabase/client";

type Course={
 id:string;name:string;region:string;city:string|null;course_type:string;art_shape:string|null;
 distance_km:number;difficulty:number;traffic_lights:number|null;toilets:number|null;
 night_recommended:boolean;route_geojson:any;tags:string[];surface:string|null;loop_type:string;
 verified:boolean;start_name:string|null;elevation_gain_m:number|null;data_quality:string;
};
type UserPos={lat:number;lng:number};
type StartLocation={lat:number;lng:number;source:"route"|"kakao";label?:string;address?:string|null};
type Toilet={id:string;name:string;lat:number;lng:number;access?:string|null;wheelchair?:string|null;opening_hours?:string|null;fee?:string|null;source?:string};
type Parking={id:string;name:string;address?:string;latitude:number;longitude:number;distance_m:number;walking_minutes:number;fee_status?:string;hours_status?:string;weekend_status?:string;source_url?:string;public_likely?:boolean};
type MobileView="map"|"list";
type SheetLevel="peek"|"half"|"full";

function courseCenter(c:Course):UserPos|null{
 const coords=(c.route_geojson?.coordinates||[]).filter((x:any)=>Array.isArray(x)&&x.length>=2);
 if(!coords.length)return null;
 const sum=coords.reduce((a:any,x:any)=>({lng:a.lng+Number(x[0]),lat:a.lat+Number(x[1])}),{lng:0,lat:0});
 return {lng:sum.lng/coords.length,lat:sum.lat/coords.length};
}
function courseStart(c:Course|null,locations:Record<string,StartLocation>):UserPos|null{
 if(!c)return null;const first=c.route_geojson?.coordinates?.[0];
 if(Array.isArray(first)&&first.length>=2&&Number.isFinite(Number(first[0]))&&Number.isFinite(Number(first[1])))return {lng:Number(first[0]),lat:Number(first[1])};
 return locations[c.id]||null;
}
function haversineKm(a:UserPos,b:UserPos){
 const R=6371,toRad=(v:number)=>v*Math.PI/180;
 const dLat=toRad(b.lat-a.lat),dLng=toRad(b.lng-a.lng);
 const s=Math.sin(dLat/2)**2+Math.cos(toRad(a.lat))*Math.cos(toRad(b.lat))*Math.sin(dLng/2)**2;
 return 2*R*Math.asin(Math.sqrt(s));
}
function nextSheetLevel(level:SheetLevel,direction:"up"|"down"):SheetLevel{
 if(direction==="up")return level==="peek"?"half":"full";
 return level==="full"?"half":"peek";
}

export default function CourseExplorer({courses,userId,favoriteIds=[]}:{courses:Course[];userId?:string|null;favoriteIds?:string[]}){
 const mapEl=useRef<HTMLDivElement|null>(null);const mapRef=useRef<any>(null);const layersRef=useRef<any[]>([]);const toiletLayersRef=useRef<any[]>([]);const parkingLayersRef=useRef<any[]>([]);const navLayersRef=useRef<any[]>([]);
 const dragStartY=useRef<number|null>(null);const draggedRef=useRef(false);
 const [q,setQ]=useState("");const [region,setRegion]=useState("");const [type,setType]=useState("");const [distance,setDistance]=useState("");
 const [surface,setSurface]=useState("");const [loop,setLoop]=useState("");const [night,setNight]=useState(false);const [verified,setVerified]=useState(false);const [lowSignals,setLowSignals]=useState(false);
 const [parkingFriendly,setParkingFriendly]=useState(false);const [parkingLoading,setParkingLoading]=useState(false);const [parkingIds,setParkingIds]=useState<Set<string>>(new Set());
 const [selected,setSelected]=useState<string|null>(null);const [mapReady,setMapReady]=useState(false);const [favorites,setFavorites]=useState(new Set(favoriteIds));const [msg,setMsg]=useState("");
 const [userPos,setUserPos]=useState<UserPos|null>(null);const [nearMode,setNearMode]=useState(false);const [locating,setLocating]=useState(false);
 const [showToilets,setShowToilets]=useState(true);const [toiletLoading,setToiletLoading]=useState(false);const [toiletCount,setToiletCount]=useState(0);
 const [showParking,setShowParking]=useState(true);const [parkingMapLoading,setParkingMapLoading]=useState(false);const [parkingCount,setParkingCount]=useState(0);
 const [courseLocations,setCourseLocations]=useState<Record<string,StartLocation>>({});const [locationsLoading,setLocationsLoading]=useState(true);
 const [mobileView,setMobileView]=useState<MobileView>("map");const [filtersOpen,setFiltersOpen]=useState(false);
 const [sheetLevel,setSheetLevel]=useState<SheetLevel>("half");const [sheetDragY,setSheetDragY]=useState(0);const [sheetDragging,setSheetDragging]=useState(false);
 const regions=useMemo(()=>Array.from(new Set(courses.map(c=>c.region))).sort(),[courses]);
 const surfaces=useMemo(()=>Array.from(new Set(courses.map(c=>c.surface).filter(Boolean) as string[])).sort(),[courses]);
 const selectedCourse=useMemo(()=>courses.find(c=>c.id===selected)||null,[courses,selected]);
 const selectedLocation=selected?courseLocations[selected]||null:null;
 const selectedStart=useMemo(()=>courseStart(selectedCourse,courseLocations),[selectedCourse,courseLocations]);
 const selectedRoutePoints=(selectedCourse?.route_geojson?.coordinates||[]).filter((x:any)=>Array.isArray(x)&&x.length>=2).length;
 const startDistanceKm=userPos&&selectedStart?haversineKm(userPos,selectedStart):null;
 const activeFilterCount=[region,type,distance,surface,loop,night,verified,lowSignals,parkingFriendly,nearMode].filter(Boolean).length;

 useEffect(()=>{let cancelled=false;(async()=>{try{const r=await fetch("/api/course-locations",{cache:"no-store"});const data=await r.json();if(!cancelled)setCourseLocations(data.locations||{});}catch{}finally{if(!cancelled)setLocationsLoading(false)}})();return()=>{cancelled=true}},[]);
 useEffect(()=>{const courseId=new URLSearchParams(window.location.search).get("course");if(courseId&&courses.some(c=>c.id===courseId)){setSelected(courseId);setSheetLevel("half");setMobileView("map");setTimeout(()=>document.getElementById("explore")?.scrollIntoView({block:"start"}),80)}},[courses]);
 useEffect(()=>{if(selected)setSheetLevel("half")},[selected]);
 const distanceMap=useMemo(()=>{const m=new Map<string,number>();if(!userPos)return m;courses.forEach(c=>{const cc=courseCenter(c)||courseLocations[c.id];if(cc)m.set(c.id,haversineKm(userPos,cc))});return m},[courses,userPos,courseLocations]);
 const filtered=useMemo(()=>{
  const rows=courses.filter(c=>{
   const text=`${c.name} ${c.region} ${c.city||""} ${c.art_shape||""} ${(c.tags||[]).join(" ")} ${c.start_name||""}`.toLowerCase();
   if(q&&!text.includes(q.toLowerCase()))return false;if(region&&c.region!==region)return false;if(type&&c.course_type!==type)return false;
   if(distance==="5"&&c.distance_km>6)return false;if(distance==="10"&&(c.distance_km<6||c.distance_km>12))return false;if(distance==="long"&&c.distance_km<12)return false;
   if(surface&&c.surface!==surface)return false;if(loop&&c.loop_type!==loop)return false;if(night&&!c.night_recommended)return false;if(verified&&!c.verified)return false;if(lowSignals&&(c.traffic_lights??99)>2)return false;
   if(parkingFriendly&&!parkingIds.has(c.id))return false;
   if(nearMode&&userPos){const d=distanceMap.get(c.id);if(d==null||d>25)return false}return true;
  });
  if(userPos&&nearMode)rows.sort((a,b)=>(distanceMap.get(a.id)??9999)-(distanceMap.get(b.id)??9999));
  return rows;
 },[courses,q,region,type,distance,surface,loop,night,verified,lowSignals,parkingFriendly,parkingIds,nearMode,userPos,distanceMap]);

 useEffect(()=>{let cancelled=false;(async()=>{if(!mapEl.current||mapRef.current)return;const L=await import("leaflet");if(cancelled||!mapEl.current)return;const map=L.map(mapEl.current,{zoomControl:true,preferCanvas:true}).setView([36.55,127.85],7);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:"© OpenStreetMap"}).addTo(map);mapRef.current=map;setMapReady(true);requestAnimationFrame(()=>map.invalidateSize(true));setTimeout(()=>map.invalidateSize(true),180)})();return()=>{cancelled=true}},[]);
 useEffect(()=>{if(!mapReady||!mapEl.current)return;const map=mapRef.current;if(!map)return;const observer=new ResizeObserver(()=>{requestAnimationFrame(()=>map.invalidateSize(false))});observer.observe(mapEl.current);const onVisibility=()=>{if(!document.hidden)setTimeout(()=>map.invalidateSize(true),30)};document.addEventListener("visibilitychange",onVisibility);window.addEventListener("resize",onVisibility);return()=>{observer.disconnect();document.removeEventListener("visibilitychange",onVisibility);window.removeEventListener("resize",onVisibility)}},[mapReady]);
 useEffect(()=>{if(mobileView!=="map"||!mapRef.current)return;setTimeout(()=>mapRef.current?.invalidateSize(true),40)},[mobileView]);

 useEffect(()=>{let cancelled=false;(async()=>{const map=mapRef.current;if(!map||!mapReady)return;requestAnimationFrame(()=>map.invalidateSize(false));const L=await import("leaflet");if(cancelled)return;layersRef.current.forEach(x=>map.removeLayer(x));layersRef.current=[];const bounds:any[]=[];
   const startIcon=(active:boolean)=>L.divIcon({className:"",html:`<div style="width:${active?34:28}px;height:${active?34:28}px;border-radius:50%;display:grid;place-items:center;background:#d9ff43;color:#111;border:3px solid #111;font-weight:900;box-shadow:0 3px 12px rgba(0,0,0,.35)">S</div>`,iconSize:[active?34:28,active?34:28],iconAnchor:[active?17:14,active?17:14]});
   const endIcon=L.divIcon({className:"",html:'<div style="width:30px;height:30px;border-radius:50%;display:grid;place-items:center;background:#ff7a86;color:#111;border:3px solid #111;font-weight:900;box-shadow:0 3px 12px rgba(0,0,0,.35)">E</div>',iconSize:[30,30],iconAnchor:[15,15]});
   filtered.forEach(c=>{
    const active=selected===c.id;const dimmed=!!selected&&!active;
    const coords=(c.route_geojson?.coordinates||[]).map((x:number[])=>[x[1],x[0]]).filter((x:any)=>Number.isFinite(x[0])&&Number.isFinite(x[1]));
    if(coords.length){const line=L.polyline(coords,{weight:active?8:dimmed?3:4,opacity:active?1:dimmed?.18:.72}).addTo(map);line.bindTooltip(`${c.name} · ${Number(c.distance_km).toFixed(1)}km`,{sticky:true});line.on("click",()=>{setSelected(c.id);setMobileView("map")});layersRef.current.push(line);coords.forEach((x:any)=>bounds.push(x));const first=coords[0];const start=L.marker(first,{icon:startIcon(active),opacity:dimmed?.45:1}).addTo(map).bindTooltip(`🏁 출발 · ${c.start_name||c.name}`);start.on("click",()=>{setSelected(c.id);setMobileView("map")});layersRef.current.push(start);
     const last=coords[coords.length-1];const distinctEnd=haversineKm({lat:first[0],lng:first[1]},{lat:last[0],lng:last[1]})>.03;if(active&&distinctEnd){const end=L.marker(last,{icon:endIcon}).addTo(map).bindTooltip("도착점");layersRef.current.push(end)}}
    else{const loc=courseLocations[c.id];if(!loc)return;const point:[number,number]=[loc.lat,loc.lng];const marker=L.marker(point,{icon:startIcon(active),opacity:dimmed?.45:1}).addTo(map).bindTooltip(`🏁 ${c.name}<br/>${c.start_name||loc.label||"출발점"}`);marker.on("click",()=>{setSelected(c.id);setMobileView("map")});layersRef.current.push(marker);bounds.push(point)}
   });
   if(selected){const c=courses.find(x=>x.id===selected);const route=(c?.route_geojson?.coordinates||[]).filter((x:any)=>Array.isArray(x)&&x.length>=2);const mobile=typeof window!=="undefined"&&window.matchMedia("(max-width: 600px)").matches;const sheetPad=mobile?(sheetLevel==="full"?390:sheetLevel==="half"?245:130):35;if(route.length){const latlngs=route.map((x:number[])=>[x[1],x[0]]);map.fitBounds(latlngs,{paddingTopLeft:[30,30],paddingBottomRight:[30,sheetPad],maxZoom:15,animate:false})}else{const loc=courseLocations[selected];if(loc){map.setView([loc.lat,loc.lng],14,{animate:false});if(mobile)map.panBy([0,-Math.max(0,(sheetPad-100)/2)],{animate:false})}}}
   else if(bounds.length){map.fitBounds(bounds,{padding:[25,25],maxZoom:filtered.length<=12?13:10,animate:false})}
   requestAnimationFrame(()=>map.invalidateSize(false));setTimeout(()=>{if(!cancelled)map.invalidateSize(false)},80)
  })();return()=>{cancelled=true}},[filtered,selected,mapReady,courseLocations,courses,sheetLevel]);

 useEffect(()=>{let cancelled=false;(async()=>{const map=mapRef.current;if(!map)return;toiletLayersRef.current.forEach(x=>map.removeLayer(x));toiletLayersRef.current=[];setToiletCount(0);if(!showToilets||!selected)return;setToiletLoading(true);try{const r=await fetch(`/api/toilets?courseId=${encodeURIComponent(selected)}`,{cache:"no-store"});const data=await r.json();if(cancelled)return;const toilets=(data.toilets||[]) as Toilet[];const L=await import("leaflet");const icon=L.divIcon({className:"",html:'<div style="width:32px;height:32px;border-radius:11px;display:grid;place-items:center;background:#238cff;color:white;border:2px solid white;box-shadow:0 3px 12px rgba(0,0,0,.35);font-size:17px">🚻</div>',iconSize:[32,32],iconAnchor:[16,16]});toilets.forEach(t=>{const details=[t.opening_hours?`운영 ${t.opening_hours}`:null,t.fee?`요금 ${t.fee}`:null,t.wheelchair?`휠체어 ${t.wheelchair}`:null].filter(Boolean).join(" · ");const marker=L.marker([t.lat,t.lng],{icon}).addTo(map).bindPopup(`<b>${t.name}</b>${details?`<br/><small>${details}</small>`:""}<br/><small>OpenStreetMap 기반</small>`);toiletLayersRef.current.push(marker)});setToiletCount(toilets.length);requestAnimationFrame(()=>map.invalidateSize(false));if(data.warning)setMsg(data.warning)}catch{if(!cancelled)setMsg("화장실 위치를 불러오지 못했습니다.")}finally{if(!cancelled)setToiletLoading(false)}})();return()=>{cancelled=true}},[selected,showToilets,mapReady]);

 useEffect(()=>{let cancelled=false;(async()=>{const map=mapRef.current;if(!map)return;parkingLayersRef.current.forEach(x=>map.removeLayer(x));parkingLayersRef.current=[];setParkingCount(0);if(!showParking||!selected)return;setParkingMapLoading(true);try{const r=await fetch(`/api/parking/nearby?courseId=${encodeURIComponent(selected)}`,{cache:"no-store"});const data=await r.json();if(cancelled)return;const rows=(data.parking||[]) as Parking[];const L=await import("leaflet");const icon=L.divIcon({className:"",html:'<div style="width:32px;height:32px;border-radius:11px;display:grid;place-items:center;background:#ffb13b;color:#111;border:2px solid white;box-shadow:0 3px 12px rgba(0,0,0,.35);font-size:17px">🚗</div>',iconSize:[32,32],iconAnchor:[16,16]});rows.forEach(p=>{const marker=L.marker([p.latitude,p.longitude],{icon}).addTo(map).bindPopup(`<b>${p.name}</b><br/><small>${p.address||"주소 확인 필요"}</small><br/><small>출발점 ${p.distance_m}m · 도보 약 ${p.walking_minutes}분 · ${p.fee_status||"요금 확인 필요"}</small>`);parkingLayersRef.current.push(marker)});setParkingCount(rows.length)}catch{if(!cancelled)setMsg("주차장 위치를 불러오지 못했습니다.")}finally{if(!cancelled)setParkingMapLoading(false)}})();return()=>{cancelled=true}},[selected,showParking,mapReady]);

 useEffect(()=>{let cancelled=false;(async()=>{const map=mapRef.current;if(!map)return;navLayersRef.current.forEach(x=>map.removeLayer(x));navLayersRef.current=[];if(!userPos)return;const L=await import("leaflet");if(cancelled)return;const userIcon=L.divIcon({className:"",html:'<div style="width:28px;height:28px;border-radius:50%;display:grid;place-items:center;background:#fff;color:#111;border:4px solid #5a8cff;box-shadow:0 3px 14px rgba(0,0,0,.4);font-size:12px">●</div>',iconSize:[28,28],iconAnchor:[14,14]});const me=L.marker([userPos.lat,userPos.lng],{icon:userIcon,zIndexOffset:900}).addTo(map).bindTooltip("현재 위치");navLayersRef.current.push(me);if(selectedStart){const guide=L.polyline([[userPos.lat,userPos.lng],[selectedStart.lat,selectedStart.lng]],{weight:4,opacity:.85,dashArray:"8 8"}).addTo(map).bindTooltip(`출발점 방향 · 직선 ${haversineKm(userPos,selectedStart).toFixed(1)}km`);navLayersRef.current.push(guide)}})();return()=>{cancelled=true}},[userPos,selectedStart,mapReady]);

 function handleSheetPointerDown(e:React.PointerEvent<HTMLButtonElement>){dragStartY.current=e.clientY;draggedRef.current=false;setSheetDragging(true);e.currentTarget.setPointerCapture(e.pointerId)}
 function handleSheetPointerMove(e:React.PointerEvent<HTMLButtonElement>){if(dragStartY.current==null)return;const delta=Math.max(-120,Math.min(120,e.clientY-dragStartY.current));if(Math.abs(delta)>5)draggedRef.current=true;setSheetDragY(delta)}
 function handleSheetPointerUp(e:React.PointerEvent<HTMLButtonElement>){if(dragStartY.current==null)return;const delta=e.clientY-dragStartY.current;if(Math.abs(delta)>=44)setSheetLevel(v=>nextSheetLevel(v,delta<0?"up":"down"));else if(!draggedRef.current)setSheetLevel(v=>v==="full"?"peek":nextSheetLevel(v,"up"));dragStartY.current=null;setSheetDragY(0);setSheetDragging(false);try{e.currentTarget.releasePointerCapture(e.pointerId)}catch{}}
 function locateMe(){const map=mapRef.current;if(!navigator.geolocation)return setMsg("현재 위치 기능을 사용할 수 없습니다.");setLocating(true);navigator.geolocation.getCurrentPosition(pos=>{const p={lat:pos.coords.latitude,lng:pos.coords.longitude};setUserPos(p);setNearMode(true);setLocating(false);setMsg(selectedStart?"현재 위치와 선택한 코스 출발점을 지도에 연결했어요. 점선은 직선 방향 안내입니다.":"현재 위치에서 25km 이내 코스를 가까운 순으로 보여드려요.");if(map){map.invalidateSize(false);if(selectedStart)map.fitBounds([[p.lat,p.lng],[selectedStart.lat,selectedStart.lng]],{padding:[45,45],maxZoom:14,animate:false});else map.setView([p.lat,p.lng],11,{animate:false})}},()=>{setLocating(false);setMsg("위치 권한을 허용하면 내 주변 코스를 추천할 수 있습니다.")},{enableHighAccuracy:false,timeout:8000,maximumAge:300000})}
 function fitMeToStart(){const map=mapRef.current;if(!map)return;if(!userPos)return locateMe();if(!selectedStart)return setMsg("이 코스의 출발점 좌표를 확인 중입니다.");map.fitBounds([[userPos.lat,userPos.lng],[selectedStart.lat,selectedStart.lng]],{padding:[50,50],maxZoom:14,animate:false});setMsg(`현재 위치 → 출발점 직선거리 ${haversineKm(userPos,selectedStart).toFixed(1)}km예요. 실제 이동 경로는 지도 앱 내비게이션을 이용해주세요.`)}
 async function toggleParkingFilter(){if(parkingFriendly){setParkingFriendly(false);return}if(parkingIds.size){setParkingFriendly(true);return}setParkingLoading(true);setMsg("출발지 근처 공영주차장을 확인하고 있어요.");try{const r=await fetch("/api/parking/coverage");const data=await r.json();const ids=new Set<string>(data.ids||[]);setParkingIds(ids);setParkingFriendly(true);setMsg(`출발점 900m 안에 공영·공공 주차장이 있는 ${ids.size}개 코스를 찾았어요.`)}catch{setMsg("주차 편한 코스 정보를 불러오지 못했습니다.")}finally{setParkingLoading(false)}}
 async function toggleFavorite(courseId:string){if(!userId){setMsg("찜하기는 로그인 후 사용할 수 있습니다.");return}const sb=createClient();const next=new Set(favorites);if(next.has(courseId)){const {error}=await sb.from("runart_favorites").delete().eq("user_id",userId).eq("course_id",courseId);if(error)return setMsg(error.message);next.delete(courseId)}else{const {error}=await sb.from("runart_favorites").insert({user_id:userId,course_id:courseId});if(error)return setMsg(error.message);next.add(courseId)}setFavorites(next);setMsg("")}
 function clearFilters(){setQ("");setRegion("");setType("");setDistance("");setSurface("");setLoop("");setNight(false);setVerified(false);setLowSignals(false);setParkingFriendly(false);setNearMode(false);setSelected(null);setMsg("필터를 초기화했어요.")}

 return <div className="explorer explorerV2" id="explore">
  <div className="exploreTitle"><div><span className="eyebrow">EXPLORE</span><h2>내 취향대로 코스 찾기</h2><p className="muted explorerSubtitle">검색부터 지도 확인, 출발까지 한 화면에서 이어집니다.</p></div><div className="exploreResultBadge"><b>{filtered.length}</b><span>개 코스</span></div></div>
  <div className="mobileExplorerTabs" role="tablist" aria-label="탐색 보기 전환"><button className={mobileView==="map"?"on":""} onClick={()=>setMobileView("map")}>🗺️ 지도</button><button className={mobileView==="list"?"on":""} onClick={()=>setMobileView("list")}>☰ 목록 <span>{filtered.length}</span></button></div>
  <div className={`filterbar explorerFilters ${filtersOpen?"open":""}`}>
   <div className="explorerSearchRow"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="지역, 코스명, 태그 검색"/><button className={`chip ${nearMode?"on":""}`} onClick={()=>nearMode?setNearMode(false):locateMe()}>{locating?"위치 찾는 중…":nearMode?"◎ 내 주변 ON":"◎ 내 주변"}</button><button className="filterToggle" onClick={()=>setFiltersOpen(v=>!v)}>⚙ 필터{activeFilterCount?` ${activeFilterCount}`:""}</button></div>
   <div className="explorerQuickChips"><button className={`chip ${parkingFriendly?"on":""}`} disabled={parkingLoading} onClick={toggleParkingFilter}>{parkingLoading?"🚗 확인 중…":parkingFriendly?"🚗 주차 ON":"🚗 주차 편함"}</button><button className={`chip ${showToilets?"on":""}`} onClick={()=>{if(!selected&&!showToilets)setMsg("먼저 지도나 목록에서 코스를 선택해주세요.");setShowToilets(v=>!v)}}>{toiletLoading?"🚻 찾는 중…":showToilets?`🚻 화장실${selected?` ${toiletCount}`:""}`:"🚻 화장실"}</button><button className={`chip ${night?"on":""}`} onClick={()=>setNight(v=>!v)}>🌙 야간</button><button className={`chip ${verified?"on":""}`} onClick={()=>setVerified(v=>!v)}>✓ 검증</button><button className={`chip ${lowSignals?"on":""}`} onClick={()=>setLowSignals(v=>!v)}>🚦 신호 적음</button></div>
   <div className="advancedFilters"><select value={region} onChange={e=>setRegion(e.target.value)}><option value="">전국</option>{regions.map(r=><option key={r}>{r}</option>)}</select><select value={type} onChange={e=>setType(e.target.value)}><option value="">전체 유형</option><option value="normal">일반</option><option value="art">그리기 런 🎨</option><option value="theme">테마런</option></select><select value={distance} onChange={e=>setDistance(e.target.value)}><option value="">거리 전체</option><option value="5">약 5K</option><option value="10">약 10K</option><option value="long">12K+</option></select><select value={surface} onChange={e=>setSurface(e.target.value)}><option value="">노면 전체</option>{surfaces.map(x=><option key={x}>{x}</option>)}</select><select value={loop} onChange={e=>setLoop(e.target.value)}><option value="">형태 전체</option><option value="loop">순환</option><option value="out_back">왕복</option><option value="point_to_point">편도</option></select><button className="chip resetChip" onClick={clearFilters}>↻ 초기화</button></div>
  </div>
  {locationsLoading&&<p className="muted explorerMessage">📍 코스 시작 위치를 불러오는 중…</p>}{msg&&<p className="muted explorerMessage">{msg}</p>}
  <div className={`mapLayout explorerLayout view-${mobileView}`}>
   <div className="mapPanel explorerMapPanel"><div className="mapFloatingActions"><button onClick={locateMe}>◎ 내 위치</button>{selected&&<button onClick={fitMeToStart}>↗ 출발점까지</button>}<button onClick={()=>setSelected(null)}>전국 보기</button></div><div ref={mapEl} className="courseMap"/>
    {selectedCourse&&<div className={`mapCourseInfo sheet-${sheetLevel} ${sheetDragging?"sheet-dragging":""}`} style={{"--sheet-drag-y":`${sheetDragY}px`} as React.CSSProperties}><button className="sheetHandle" aria-label="코스 정보 패널 크기 조절" onPointerDown={handleSheetPointerDown} onPointerMove={handleSheetPointerMove} onPointerUp={handleSheetPointerUp} onPointerCancel={handleSheetPointerUp}><span/><small>{sheetLevel==="peek"?"위로 밀어 보기":sheetLevel==="full"?"아래로 밀어 지도 보기":"위로 상세 · 아래로 축소"}</small></button><button className="mapCourseClose" aria-label="선택 해제" onClick={()=>setSelected(null)}>×</button><div className="mapCourseTitle"><div><small>{selectedCourse.region} {selectedCourse.city||""}</small><h3>{selectedCourse.name}</h3>{selectedCourse.start_name&&<p>🏁 출발 {selectedCourse.start_name}</p>}{selectedLocation&&<p className="mapCoords">좌표 {selectedLocation.lat.toFixed(6)}, {selectedLocation.lng.toFixed(6)} {selectedLocation.source==="kakao"?"· 시작점 기준":"· GPS 경로 기준"}</p>}{startDistanceKm!=null&&<p>◎ 내 위치에서 출발점 직선 {startDistanceKm.toFixed(1)}km</p>}</div><strong>{Number(selectedCourse.distance_km).toFixed(1)}K</strong></div><div className="runnerFlowStrip"><span><b>🏁 출발</b><small>{selectedCourse.start_name||"출발점"}</small></span><span><b>🧭 경로</b><small>{selectedRoutePoints?`${selectedRoutePoints}개 지점`:"시작점 기준"}</small></span><span><b>🚻 화장실</b><small>{toiletLoading?"조회 중":showToilets?`${toiletCount}곳`:"숨김"}</small></span><button type="button" onClick={()=>setShowParking(v=>!v)}><b>🚗 주차</b><small>{parkingMapLoading?"조회 중":showParking?`${parkingCount}곳":"숨김"}</small></button><Link href={`/courses/${selectedCourse.id}#after-run`}><b>🍚 RUN+EAT</b><small>러닝 후 장소</small></Link></div><div className="mapCourseStats"><span>난이도 {"★".repeat(selectedCourse.difficulty||2)}</span><span>🚦 {selectedCourse.traffic_lights??"-"}</span><span>🚻 {showToilets?toiletCount:(selectedCourse.toilets??"-")}</span>{showParking&&parkingCount>0&&<span>🚗 {parkingCount}곳</span>}{selectedCourse.elevation_gain_m!=null&&<span>↗ {selectedCourse.elevation_gain_m}m</span>}{selectedCourse.night_recommended&&<span>🌙 야간추천</span>}</div><div className="mapCourseTags">{(selectedCourse.tags||[]).slice(0,3).map(t=><span key={t}>#{t}</span>)}</div><div className="sheetExpandedDetail"><div><span>코스 형태</span><b>{selectedCourse.loop_type==="loop"?"순환":selectedCourse.loop_type==="out_back"?"왕복":"편도"}</b></div><div><span>노면</span><b>{selectedCourse.surface||"정보 없음"}</b></div><div><span>데이터</span><b>{selectedCourse.verified?"검증 완료":selectedCourse.data_quality||"확인 중"}</b></div></div><div className="mapCourseActions explorerMapActions"><Link href={`/courses/${selectedCourse.id}`}>상세 정보</Link><Link href={`/courses/${selectedCourse.id}#run-start`}>🏁 출발 준비</Link><Link href={`/courses/${selectedCourse.id}#after-run`}>🍚 RUN+EAT</Link><button onClick={()=>toggleFavorite(selectedCourse.id)}>{favorites.has(selectedCourse.id)?"♥":"♡"}</button></div></div>}
    <p className="mapDataNote">S는 출발, E는 도착입니다. 선택한 코스는 강조되고 화장실·주차장이 색상별 마커로 표시됩니다.</p>
   </div>
   <div className="courseList explorerCourseList"><div className="listHead"><div><b>{filtered.length}개 코스</b><span className="muted">{nearMode?"가까운 순":parkingFriendly?"주차 편한 코스":"추천 순으로 둘러보세요"}</span></div>{activeFilterCount>0&&<button className="textReset" onClick={clearFilters}>필터 초기화</button>}</div>
    {filtered.map(c=>{const away=distanceMap.get(c.id);const hasRoute=(c.route_geojson?.coordinates||[]).length>0;const hasLocation=!!courseLocations[c.id];return <article key={c.id} className={`courseCard explorerCourseCard ${selected===c.id?"selected":""}`} onClick={()=>{setSelected(c.id);setMobileView("map")}}><div className="courseTop"><div><h3>{c.name} {c.verified&&<span className="done">✓</span>}</h3><p className="muted">{c.region} {c.city||""}{c.start_name?` · ${c.start_name}`:""}{nearMode&&away!=null?` · 내 위치 ${away.toFixed(1)}km`:""}</p></div><div className="courseCardActions"><b>{Number(c.distance_km).toFixed(1)}K</b><button aria-label="찜하기" className={`iconHeart ${favorites.has(c.id)?"saved":""}`} onClick={e=>{e.stopPropagation();toggleFavorite(c.id)}}>{favorites.has(c.id)?"♥":"♡"}</button></div></div><div className="metaRow"><span className="tag">{hasRoute?"🧭 GPS 경로":"📍 시작점"}{!hasRoute&&!hasLocation&&!locationsLoading?" 확인중":""}</span>{parkingIds.has(c.id)&&<span className="tag">🚗 주차 편함</span>}{c.course_type==="art"&&<span className="tag">🎨 {c.art_shape||"GPS ART"}</span>}<span>난이도 {"★".repeat(c.difficulty||2)}</span>{c.surface&&<span>노면 {c.surface}</span>}{c.elevation_gain_m!=null&&<span>↗ {c.elevation_gain_m}m</span>}<span>🚦 {c.traffic_lights??"-"}</span><span>🚻 {selected===c.id&&showToilets?toiletCount:(c.toilets??"-")}</span>{c.night_recommended&&<span>🌙</span>}</div><div className="metaRow tagRow">{(c.tags||[]).slice(0,4).map(t=><span className="tag" key={t}>#{t}</span>)}</div><div className="courseListActions"><button onClick={e=>{e.stopPropagation();setSelected(c.id);setMobileView("map")}}>지도에서 보기</button><Link href={`/courses/${c.id}`} onClick={e=>e.stopPropagation()}>상세 · 출발 준비 →</Link></div></article>})}
    {!filtered.length&&<div className="empty explorerEmpty"><b>조건에 맞는 코스가 없어요.</b><p>필터를 조금 줄이거나 전국으로 다시 찾아보세요.</p><button className="btn ghost" onClick={clearFilters}>필터 초기화</button></div>}
   </div>
  </div>
 </div>
}