"use client";
import {useState} from "react";
import {useRouter} from "next/navigation";
import {createClient} from "@/lib/supabase/client";

type Member={user_id:string;display_name:string;role:string};
type Course={id:string;name:string;distance_km:number};
export default function EditRunLogForm({logId,initialCourseId,initialDate,initialDistance,initialMemo,initialParticipants,courses,members}:{logId:string;initialCourseId:string;initialDate:string;initialDistance:number|null;initialMemo:string|null;initialParticipants:string[];courses:Course[];members:Member[]}){
 const [courseId,setCourseId]=useState(initialCourseId);const [date,setDate]=useState(initialDate);const [distance,setDistance]=useState(initialDistance?.toString()||"");const [memo,setMemo]=useState(initialMemo||"");const [selected,setSelected]=useState<string[]>(initialParticipants);const [msg,setMsg]=useState("");const router=useRouter();
 function toggle(id:string){setSelected(x=>x.includes(id)?x.filter(v=>v!==id):[...x,id])}
 async function save(){const sb=createClient();const course=courses.find(c=>c.id===courseId);const {error}=await sb.from("runart_course_logs").update({course_id:courseId,run_date:date,actual_distance_km:distance?Number(distance):course?.distance_km,memo:memo||null,updated_at:new Date().toISOString()}).eq("id",logId);if(error)return setMsg(error.message);const del=await sb.from("runart_log_participants").delete().eq("log_id",logId);if(del.error)return setMsg(del.error.message);if(selected.length){const ins=await sb.from("runart_log_participants").insert(selected.map(user_id=>({log_id:logId,user_id})));if(ins.error)return setMsg(ins.error.message)}setMsg("수정 완료");setTimeout(()=>{router.push("/dashboard");router.refresh()},500)}
 async function remove(){if(!confirm("이 러닝 기록을 삭제할까요?"))return;const sb=createClient();const {error}=await sb.from("runart_course_logs").delete().eq("id",logId);if(error)return setMsg(error.message);router.push("/dashboard");router.refresh()}
 return <div className="card editRunLogCard"><h3>러닝 기록 편집</h3><div className="editLogFields"><label>코스<select value={courseId} onChange={e=>setCourseId(e.target.value)}>{courses.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>날짜<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>실제 거리(km)<input type="number" step="0.01" value={distance} onChange={e=>setDistance(e.target.value)}/></label><label className="editLogMemo">메모<textarea value={memo} onChange={e=>setMemo(e.target.value)} placeholder="러닝 메모를 입력하세요."/></label></div><div className="attendanceBox"><b>실제 참여자</b><div className="attendanceGrid" style={{marginTop:10}}>{members.map(m=><label className={`memberCheck ${selected.includes(m.user_id)?"checked":""}`} key={m.user_id}><input type="checkbox" checked={selected.includes(m.user_id)} onChange={()=>toggle(m.user_id)}/><span><b>{m.display_name}</b><small>{m.role}</small></span></label>)}</div></div><div className="actions editLogActions"><button className="btn" type="button" onClick={save}>수정 내용 저장</button><button className="btn danger" type="button" onClick={remove}>기록 삭제</button></div>{msg&&<p className="muted" role="status">{msg}</p>}</div>
}
