"use client";
import {useState} from "react";
import {useRouter} from "next/navigation";
import {createClient} from "@/lib/supabase/client";

type Member={user_id:string;display_name:string;role:string};
type Course={id:string;name:string;distance_km:number};
export default function EditRunLogForm({logId,initialCourseId,initialDate,initialDistance,initialMemo,initialParticipants,courses,members}:{logId:string;initialCourseId:string;initialDate:string;initialDistance:number|null;initialMemo:string|null;initialParticipants:string[];courses:Course[];members:Member[]}){
 const [courseId,setCourseId]=useState(initialCourseId);const [date,setDate]=useState(initialDate);const [distance,setDistance]=useState(initialDistance?.toString()||"");const [memo,setMemo]=useState(initialMemo||"");const [selected,setSelected]=useState<string[]>(initialParticipants);const [msg,setMsg]=useState("");const [busy,setBusy]=useState<"save"|"delete"|null>(null);const router=useRouter();
 function toggle(id:string){setSelected(x=>x.includes(id)?x.filter(v=>v!==id):[...x,id])}
 async function save(){if(busy)return;const parsedDistance=distance.trim()===""?null:Number(distance);if(parsedDistance!=null&&(!Number.isFinite(parsedDistance)||parsedDistance<=0))return setMsg("실제 거리는 0보다 큰 숫자로 입력해주세요.");setBusy("save");setMsg("");const sb=createClient();try{const course=courses.find(c=>c.id===courseId);const {error}=await sb.from("runart_course_logs").update({course_id:courseId,run_date:date,actual_distance_km:parsedDistance??course?.distance_km,memo:memo.trim()||null,updated_at:new Date().toISOString()}).eq("id",logId);if(error)throw error;const del=await sb.from("runart_log_participants").delete().eq("log_id",logId);if(del.error)throw del.error;if(selected.length){const ins=await sb.from("runart_log_participants").insert(selected.map(user_id=>({log_id:logId,user_id})));if(ins.error)throw ins.error}setMsg("수정했습니다. 기록 화면으로 이동합니다.");setTimeout(()=>{router.push("/dashboard");router.refresh()},500)}catch(e:any){setMsg(e?.message||"기록 수정 중 오류가 발생했습니다.");setBusy(null)}}
 async function remove(){if(busy||!confirm("이 러닝 기록을 삭제할까요? 삭제한 기록은 복구할 수 없습니다."))return;setBusy("delete");setMsg("");const sb=createClient();const {error}=await sb.from("runart_course_logs").delete().eq("id",logId);if(error){setMsg(error.message);setBusy(null);return}router.push("/dashboard");router.refresh()}
 return <div className="card editRunLogCard"><h3>러닝 기록 편집</h3><div className="editLogFields"><label>코스<select disabled={!!busy} value={courseId} onChange={e=>setCourseId(e.target.value)}>{courses.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>날짜<input disabled={!!busy} type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>실제 거리(km)<input disabled={!!busy} type="number" min="0.01" step="0.01" inputMode="decimal" value={distance} onChange={e=>setDistance(e.target.value)}/></label><label className="editLogMemo">메모<textarea disabled={!!busy} value={memo} onChange={e=>setMemo(e.target.value)} placeholder="러닝 메모를 입력하세요."/></label></div><div className="attendanceBox"><b>실제 참여자</b><div className="attendanceGrid" style={{marginTop:10}}>{members.map(m=><label className={`memberCheck ${selected.includes(m.user_id)?"checked":""}`} key={m.user_id}><input disabled={!!busy} type="checkbox" checked={selected.includes(m.user_id)} onChange={()=>toggle(m.user_id)}/><span><b>{m.display_name}</b><small>{m.role}</small></span></label>)}</div></div><div className="actions editLogActions"><button className="btn" disabled={!!busy} type="button" onClick={save}>{busy==="save"?"저장 중…":"수정 내용 저장"}</button><button className="btn danger" disabled={!!busy} type="button" onClick={remove}>{busy==="delete"?"삭제 중…":"기록 삭제"}</button></div>{msg&&<p className="muted formStatus" role="status" aria-live="polite">{msg}</p>}</div>
}
