"use client";
import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {createClient} from "@/lib/supabase/client";

type Race={source_key:string;name:string;race_date:string;region:string|null;distance_options:string[];registration_start?:string|null;registration_deadline:string|null;registration_status:string;official_url:string|null;registration_url?:string|null;registration_text?:string|null;source_name:string;source_url:string;source_kind?:string};
type Saved={source_key:string;race_name:string;race_date:string|null;region:string|null;official_url:string|null;status:string;distance:string|null;note:string|null};
const STATUS:{[k:string]:string}={interested:"관심",applied:"신청완료",going:"참가예정",not_going:"불참"},REG:{[k:string]:string}={open:"접수중",closed:"접수마감",upcoming:"접수예정",unknown:"접수확인"};
function dday(date:string){const a=new Date(`${date}T00:00:00+09:00`).getTime(),b=new Date();b.setHours(0,0,0,0);const d=Math.ceil((a-b.getTime())/86400000);return d===0?"D-DAY":d>0?`D-${d}`:"종료"}
function legacyKey(r:Race){return `${r.name.replace(/\s/g,"").toLowerCase()}|${r.race_date}`}
function sourceLabel(name:string){return name==="kimrunning"?"김러닝":name==="runfor"?"RUNFOR":name==="marathonmoa"?"마라톤모아":name==="community"?"러너 제보":"Rung"}

export default function PublicRaceBrowser({userId,initialSaved,initialMineOnly=false}:{userId:string|null;initialSaved:Saved[];initialMineOnly?:boolean}){
 const[races,setRaces]=useState<Race[]>([]),[saved,setSaved]=useState(new Map(initialSaved.map(x=>[x.source_key,x]))),[loading,setLoading]=useState(true),[error,setError]=useState(""),[q,setQ]=useState(""),[region,setRegion]=useState(""),[status,setStatus]=useState(""),[mineOnly,setMineOnly]=useState(initialMineOnly),[formsOnly,setFormsOnly]=useState(false),[busy,setBusy]=useState(""),[noteOpen,setNoteOpen]=useState(""),[noteDraft,setNoteDraft]=useState(""),[meta,setMeta]=useState({count:0,formCount:0});
 const legacySaved=useMemo(()=>new Map(Array.from(saved.values()).map(x=>[`${x.race_name.replace(/\s/g,"").toLowerCase()}|${x.race_date||""}`,x])),[saved]);
 function savedFor(r:Race){return saved.get(r.source_key)||legacySaved.get(legacyKey(r))}
 async function load(){setLoading(true);setError("");try{const r=await fetch("/api/races/live",{cache:"no-store"}),j=await r.json();if(!r.ok)throw new Error(j?.error||j?.partial_errors?.join(" · ")||"대회 정보를 불러오지 못했습니다.");setRaces(j.races||[]);setMeta({count:j.count||0,formCount:j.google_form_count||0})}catch(e:any){setError(e?.message||"대회 정보를 불러오지 못했습니다.")}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 const regions=useMemo(()=>Array.from(new Set(races.map(x=>x.region).filter(Boolean) as string[])).sort(),[races]);
 const filtered=useMemo(()=>races.filter(r=>{if(q&&!`${r.name} ${r.region||""} ${(r.distance_options||[]).join(" ")}`.toLowerCase().includes(q.toLowerCase()))return false;if(region&&r.region!==region)return false;if(status&&r.registration_status!==status)return false;if(mineOnly&&!savedFor(r))return false;if(formsOnly&&!r.registration_url)return false;return true}),[races,q,region,status,mineOnly,formsOnly,saved,legacySaved]);
 async function saveRace(r:Race,nextStatus:string,distance?:string,note?:string){if(!userId)return;setBusy(r.source_key);const sb=createClient(),prev=savedFor(r),payload={user_id:userId,source_key:r.source_key,race_name:r.name,race_date:r.race_date||null,region:r.region||null,official_url:r.official_url||r.registration_url||null,status:nextStatus,distance:distance??prev?.distance??null,note:note??prev?.note??null,updated_at:new Date().toISOString()};const{error}=await sb.from("runart_public_race_participation").upsert(payload,{onConflict:"user_id,source_key"});if(!error){const next=new Map(saved);if(prev&&prev.source_key!==r.source_key)next.delete(prev.source_key);next.set(r.source_key,payload as Saved);setSaved(next)}setBusy("")}
 async function removeRace(r:Race){if(!userId)return;const me=savedFor(r);if(!me)return;setBusy(r.source_key);const sb=createClient(),{error}=await sb.from("runart_public_race_participation").delete().eq("user_id",userId).eq("source_key",me.source_key);if(!error){const next=new Map(saved);next.delete(me.source_key);setSaved(next);setNoteOpen("")}setBusy("")}
 return <div className="publicRaceBrowser">
  <div className="raceFinderBar"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="대회명·지역·거리 검색"/><select value={region} onChange={e=>setRegion(e.target.value)}><option value="">전국</option>{regions.map(x=><option key={x}>{x}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">접수상태 전체</option><option value="open">접수중</option><option value="upcoming">접수예정</option><option value="closed">접수마감</option><option value="unknown">확인필요</option></select><button className={`chip ${formsOnly?"on":""}`} onClick={()=>setFormsOnly(v=>!v)}>Google Form {meta.formCount?`· ${meta.formCount}`:""}</button>{userId&&<button className={`chip ${mineOnly?"on":""}`} onClick={()=>setMineOnly(v=>!v)}>★ 내 대회</button>}</div>
  <div className="raceSourceRow"><span>{loading?"대회 정보를 업데이트하는 중…":`${filtered.length}개 대회 · 4개 공개 일정 + 러너 제보 통합`}</span><div><Link className="textReset" href={userId?"/races/my":"/login"}>{userId?"내 일정":"로그인"}</Link><button className="textReset" onClick={load}>↻ 새로고침</button></div></div>
  {error&&<div className="card raceError"><b>실시간 대회 정보를 불러오지 못했어요.</b><p>{error}</p><button className="btn ghost" onClick={load}>다시 시도</button></div>}
  <div className="raceLiveList">{filtered.map(r=>{const me=savedFor(r),editing=noteOpen===r.source_key;return <article className={`card raceLiveCard ${me?"savedRace":""}`} key={r.source_key}><div className="raceDateBox"><b>{new Date(`${r.race_date}T00:00:00+09:00`).getMonth()+1}/{new Date(`${r.race_date}T00:00:00+09:00`).getDate()}</b><small>{dday(r.race_date)}</small></div><div className="raceLiveBody"><div className="raceLiveTitle"><div><h3>{r.name}</h3><p>{r.region||"지역 미정"} · {r.race_date} · {sourceLabel(r.source_name)}</p></div><span className={`raceRegStatus ${r.registration_status}`}>{REG[r.registration_status]||"확인"}</span></div><div className="raceTags">{r.registration_url&&<span className="tag mine">Google Form 접수</span>}{r.source_kind==="community"&&<span className="tag">러너 제보</span>}{r.distance_options.map(d=><span className="tag" key={d}>{d}</span>)}{r.registration_start&&<span>접수 {r.registration_start}</span>}{r.registration_deadline&&<span>마감 {r.registration_deadline}</span>}{me&&<span className="tag mine">내 상태 · {STATUS[me.status]||me.status}</span>}</div>{r.registration_text&&<p className="raceRegistrationText">{r.registration_text}</p>}<div className="raceCardActions">{userId?<><button className={me?.status==="interested"?"on":""} disabled={busy===r.source_key} onClick={()=>saveRace(r,"interested")}>관심</button><button className={me?.status==="applied"?"on":""} disabled={busy===r.source_key} onClick={()=>saveRace(r,"applied")}>신청완료</button><button className={me?.status==="going"?"on":""} disabled={busy===r.source_key} onClick={()=>saveRace(r,"going")}>참가예정</button></>:<Link className="raceLoginLink" href="/login">로그인 후 참가 기록</Link>}{r.registration_url&&<a className="raceGoogleForm" href={r.registration_url} target="_blank" rel="noreferrer">Google Form 신청 ↗</a>}{r.official_url&&r.official_url!==r.registration_url&&<a href={r.official_url} target="_blank" rel="noreferrer">대회 정보 ↗</a>}</div>{userId&&me&&<div className="racePersonalRow">{r.distance_options.length>0&&<label className="raceDistanceSelect">내 종목<select value={me.distance||""} onChange={e=>saveRace(r,me.status,e.target.value)}><option value="">선택</option>{r.distance_options.map(d=><option key={d}>{d}</option>)}</select></label>}<button className="textReset" onClick={()=>{setNoteOpen(editing?"":r.source_key);setNoteDraft(me.note||"")}}>메모</button><button className="textReset dangerText" disabled={busy===r.source_key} onClick={()=>removeRace(r)}>기록 해제</button></div>}{editing&&me&&<div className="raceNoteEditor"><textarea value={noteDraft} onChange={e=>setNoteDraft(e.target.value)} placeholder="집결 시간, 교통, 준비물 등을 메모하세요." maxLength={300}/><div><button className="btn ghost" onClick={()=>setNoteOpen("")}>취소</button><button className="btn" disabled={busy===r.source_key} onClick={async()=>{await saveRace(r,me.status,me.distance||undefined,noteDraft.trim());setNoteOpen("")}}>메모 저장</button></div></div>}</div></article>})}</div>
  {!loading&&!error&&!filtered.length&&<div className="card emptyState"><b>{mineOnly?"저장한 대회가 없어요.":formsOnly?"현재 확인된 Google Form 대회가 없어요.":"조건에 맞는 대회가 없어요."}</b><p className="muted">검색어나 필터를 바꿔보세요.</p></div>}
  <p className="raceSourceNote">Rung·김러닝·RUNFOR·마라톤모아와 승인된 러너 제보를 통합합니다. Google Form 접수 대회도 링크가 공개된 경우 함께 표시합니다. 실제 일정과 접수 여부는 신청 페이지에서 최종 확인해주세요.</p>
 </div>
}
