"use client";

import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {createClient} from "@/lib/supabase/client";

type Race={source_key:string;name:string;race_date:string;region:string|null;distance_options:string[];registration_deadline:string|null;registration_status:string;official_url:string|null;registration_url?:string|null;registration_text?:string|null;source_name:string;source_url:string};
type Saved={source_key:string;race_name:string;race_date:string|null;region:string|null;official_url:string|null;status:string;distance:string|null;note:string|null};
const REG:Record<string,string>={open:"접수중",closed:"접수마감",upcoming:"접수예정",unknown:"접수확인"};
const DISTANCE_FILTERS=["전체","Full","Half","10K","5K","기타"] as const;type DistanceFilter=(typeof DISTANCE_FILTERS)[number];
function normalizeDistance(v:string|null|undefined){return v?.trim().toLowerCase()==="ultra"?"Full":v||""}
function monthKey(date:string){return date?.slice(0,7)||""}
function monthLabel(key:string){const[y,m]=key.split("-");return y&&m?`${y}년 ${Number(m)}월`:"일정 미정"}
function weekday(date:string){return new Intl.DateTimeFormat("ko-KR",{weekday:"short",timeZone:"Asia/Seoul"}).format(new Date(`${date}T00:00:00+09:00`))}
function dayOfMonth(date:string){return Number(date?.slice(8,10)||0)}
function dday(date:string){const a=new Date(`${date}T00:00:00+09:00`).getTime(),b=new Date();b.setHours(0,0,0,0);const d=Math.ceil((a-b.getTime())/86400000);return d===0?"D-DAY":d>0?`D-${d}`:"종료"}
function distanceMatches(r:Race,filter:DistanceFilter):boolean{if(filter==="전체")return true;const values=(r.distance_options||[]).map(d=>normalizeDistance(d).toLowerCase()),joined=values.join(" ");if(filter==="Full")return /(^|\s)(full|42k|42\.195k|42\.195)(\s|$)/i.test(joined);if(filter==="Half")return /(^|\s)(half|21k|21\.0975k)(\s|$)/i.test(joined);if(filter==="10K")return values.some(v=>/^10k$/i.test(v));if(filter==="5K")return values.some(v=>/^5k$/i.test(v));return !distanceMatches(r,"Full")&&!distanceMatches(r,"Half")&&!distanceMatches(r,"10K")&&!distanceMatches(r,"5K")}

export default function PublicRaceBrowser({userId,initialSaved,initialMineOnly=false}:{userId:string|null;initialSaved:Saved[];initialMineOnly?:boolean}){
 const[races,setRaces]=useState<Race[]>([]),[saved,setSaved]=useState(new Map(initialSaved.map(x=>[x.source_key,x]))),[loading,setLoading]=useState(true),[error,setError]=useState(""),[q,setQ]=useState(""),[region,setRegion]=useState(""),[status,setStatus]=useState(""),[mineOnly,setMineOnly]=useState(initialMineOnly),[distanceFilter,setDistanceFilter]=useState<DistanceFilter>("전체"),[selectedMonth,setSelectedMonth]=useState("");
 async function load(force=false){setLoading(true);setError("");try{const key="ttwittun:races:live:v4";if(!force){const raw=sessionStorage.getItem(key);if(raw){const c=JSON.parse(raw);if(Date.now()-c.at<600000){setRaces(c.races||[]);setLoading(false);return}}}const res=await fetch("/api/races/live",{cache:"force-cache"}),j=await res.json();if(!res.ok)throw new Error("대회 정보를 불러오지 못했습니다.");const next=j.races||[];setRaces(next);sessionStorage.setItem(key,JSON.stringify({at:Date.now(),races:next}))}catch(e:any){setError(e?.message||"대회 정보를 불러오지 못했습니다.")}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 const months=useMemo(()=>Array.from(new Set(races.map(r=>monthKey(r.race_date)).filter(Boolean))).sort(),[races]);
 useEffect(()=>{if(selectedMonth||!months.length)return;const now=new Date(),cur=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,"0")}`;setSelectedMonth(months.includes(cur)?cur:(months.find(m=>m>=cur)||months[0]))},[months,selectedMonth]);
 const monthIndex=months.indexOf(selectedMonth),regions=useMemo(()=>Array.from(new Set(races.map(r=>r.region).filter(Boolean) as string[])).sort(),[races]);
 const filtered=useMemo(()=>races.filter(r=>{if(selectedMonth&&monthKey(r.race_date)!==selectedMonth)return false;if(q&&!`${r.name} ${r.region||""} ${(r.distance_options||[]).join(" ")}`.toLowerCase().includes(q.toLowerCase()))return false;if(region&&r.region!==region)return false;if(status&&r.registration_status!==status)return false;if(mineOnly&&!saved.has(r.source_key))return false;if(!distanceMatches(r,distanceFilter))return false;return true}).sort((a,b)=>a.race_date.localeCompare(b.race_date)),[races,selectedMonth,q,region,status,mineOnly,distanceFilter,saved]);
 async function setParticipation(r:Race,nextStatus:string){if(!userId)return;const sb=createClient(),prev=saved.get(r.source_key);const payload={user_id:userId,source_key:r.source_key,race_name:r.name,race_date:r.race_date,region:r.region,official_url:r.official_url||r.registration_url||null,status:nextStatus,distance:prev?.distance||null,note:prev?.note||null,updated_at:new Date().toISOString()};const{error}=await sb.from("runart_public_race_participation").upsert(payload,{onConflict:"user_id,source_key"});if(!error){const next=new Map(saved);next.set(r.source_key,payload as Saved);setSaved(next)}}
 return <div className="publicRaceBrowser raceListV2">
  <div className="raceFinderBar"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="대회명·지역·거리 검색"/><select value={region} onChange={e=>setRegion(e.target.value)}><option value="">전국</option>{regions.map(x=><option key={x}>{x}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">접수상태 전체</option><option value="open">접수중</option><option value="upcoming">접수예정</option><option value="closed">접수마감</option><option value="unknown">확인필요</option></select>{userId&&<button type="button" className={`chip ${mineOnly?"on":""}`} onClick={()=>setMineOnly(v=>!v)}>내 대회</button>}</div>
  <div className="raceDistanceTabs">{DISTANCE_FILTERS.map(item=><button key={item} type="button" className={distanceFilter===item?"active":""} onClick={()=>setDistanceFilter(item)}>{item}</button>)}</div>
  <div className="raceMonthNavigator"><button type="button" disabled={monthIndex<=0} onClick={()=>setSelectedMonth(months[monthIndex-1])}>‹</button><div><small>{selectedMonth?.slice(0,4)||new Date().getFullYear()}년</small><strong>{selectedMonth?Number(selectedMonth.slice(5,7)):new Date().getMonth()+1}월</strong></div><button type="button" disabled={monthIndex<0||monthIndex>=months.length-1} onClick={()=>setSelectedMonth(months[monthIndex+1])}>›</button></div>
  <div className="raceSourceRow"><span>{loading?"대회 정보를 업데이트하는 중…":`${filtered.length}개 일정`}</span><div><Link className="textReset" href={userId?"/races/my":"/login"} prefetch>{userId?"내 일정":"로그인"}</Link><button className="textReset" type="button" onClick={()=>load(true)}>새로고침</button></div></div>
  {error&&<div className="card raceError"><b>{error}</b></div>}
  <div className="raceMonthCards">{filtered.map(r=>{const me=saved.get(r.source_key);return <article className={`raceListItem ${me?"savedRace":""}`} key={r.source_key}><div className="raceListDate"><b>{dayOfMonth(r.race_date)}일</b><span>{weekday(r.race_date)}</span></div><div className="raceListContent"><div className="raceListTitleRow"><div><p>{r.region||"지역 미정"}</p><h3>{r.name}</h3></div><span className={`raceRegStatus ${r.registration_status}`}>{REG[r.registration_status]||"확인"}</span></div><div className="raceListDistances">{(r.distance_options||[]).map(d=><span key={d}>{normalizeDistance(d)}</span>)}</div><div className="raceListMeta">{r.registration_deadline&&<span>마감 {r.registration_deadline}</span>}<span>{dday(r.race_date)}</span></div>{r.registration_text&&<p className="raceListDescription">{r.registration_text}</p>}{userId&&<div className="raceParticipationLine"><button type="button" className={me?.status==="applied"?"active":""} onClick={()=>setParticipation(r,"applied")}><span className="miniCheck">{me?.status==="applied"?"✓":""}</span>신청완료</button><button type="button" className={me?.status==="going"?"active":""} onClick={()=>setParticipation(r,"going")}><span className="miniCheck">{me?.status==="going"?"✓":""}</span>참가예정</button></div>}<div className="racePrimaryLinks">{r.registration_url&&<a href={r.registration_url} target="_blank" rel="noreferrer">신청</a>}{r.official_url&&<a href={r.official_url} target="_blank" rel="noreferrer">대회 정보</a>}</div></div></article>})}</div>
  {!loading&&!error&&!filtered.length&&<div className="card emptyState"><b>{monthLabel(selectedMonth)} 일정이 없어요.</b><p className="muted">좌우 버튼으로 다른 달을 확인해보세요.</p></div>}
 </div>
}
