"use client";
import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {createClient} from "@/lib/supabase/client";

type Race={source_key:string;name:string;race_date:string;region:string|null;distance_options:string[];registration_start?:string|null;registration_deadline:string|null;registration_status:string;official_url:string|null;registration_text?:string|null;source_name:string;source_url:string};
type Saved={source_key:string;race_name:string;race_date:string|null;region:string|null;official_url:string|null;status:string;distance:string|null;note:string|null};

const STATUS:{[k:string]:string}={interested:"관심",applied:"신청완료",going:"참가예정",not_going:"불참"};
const REG:{[k:string]:string}={open:"접수중",closed:"접수마감",upcoming:"접수예정",unknown:"접수확인"};
function dday(date:string){const a=new Date(`${date}T00:00:00+09:00`).getTime(),b=new Date();b.setHours(0,0,0,0);const d=Math.ceil((a-b.getTime())/86400000);return d===0?"D-DAY":d>0?`D-${d}`:"종료"}

export default function PublicRaceBrowser({userId,initialSaved}:{userId:string|null;initialSaved:Saved[]}){
 const[races,setRaces]=useState<Race[]>([]),[saved,setSaved]=useState(new Map(initialSaved.map(x=>[x.source_key,x]))),[loading,setLoading]=useState(true),[error,setError]=useState(""),[q,setQ]=useState(""),[region,setRegion]=useState(""),[status,setStatus]=useState(""),[mineOnly,setMineOnly]=useState(false),[busy,setBusy]=useState("");
 async function load(){setLoading(true);setError("");try{const r=await fetch("/api/races/live",{cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j?.error||"대회 정보를 불러오지 못했습니다.");setRaces(j.races||[])}catch(e:any){setError(e?.message||"대회 정보를 불러오지 못했습니다.")}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 const regions=useMemo(()=>Array.from(new Set(races.map(x=>x.region).filter(Boolean) as string[])).sort(),[races]);
 const filtered=useMemo(()=>races.filter(r=>{if(q&&!`${r.name} ${r.region||""} ${(r.distance_options||[]).join(" ")}`.toLowerCase().includes(q.toLowerCase()))return false;if(region&&r.region!==region)return false;if(status&&r.registration_status!==status)return false;if(mineOnly&&!saved.has(r.source_key))return false;return true}),[races,q,region,status,mineOnly,saved]);
 async function saveRace(r:Race,nextStatus:string,distance?:string){if(!userId)return;setBusy(r.source_key);const sb=createClient(),prev=saved.get(r.source_key);const payload={user_id:userId,source_key:r.source_key,race_name:r.name,race_date:r.race_date||null,region:r.region||null,official_url:r.official_url||null,status:nextStatus,distance:distance??prev?.distance??null,note:prev?.note??null,updated_at:new Date().toISOString()};const{error}=await sb.from("runart_public_race_participation").upsert(payload,{onConflict:"user_id,source_key"});if(!error)setSaved(new Map(saved).set(r.source_key,payload as Saved));setBusy("")}
 return <div className="publicRaceBrowser">
  <div className="raceFinderBar"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="대회명·지역·거리 검색"/><select value={region} onChange={e=>setRegion(e.target.value)}><option value="">전국</option>{regions.map(x=><option key={x}>{x}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">접수상태 전체</option><option value="open">접수중</option><option value="upcoming">접수예정</option><option value="closed">접수마감</option><option value="unknown">확인필요</option></select>{userId&&<button className={`chip ${mineOnly?"on":""}`} onClick={()=>setMineOnly(v=>!v)}>★ 내 대회</button>}</div>
  <div className="raceSourceRow"><span>{loading?"대회 정보를 업데이트하는 중…":`${filtered.length}개 대회`}</span><button className="textReset" onClick={load}>↻ 새로고침</button></div>
  {error&&<div className="card raceError"><b>실시간 대회 정보를 불러오지 못했어요.</b><p>{error}</p><button className="btn ghost" onClick={load}>다시 시도</button></div>}
  <div className="raceLiveList">{filtered.map(r=>{const me=saved.get(r.source_key);return <article className={`card raceLiveCard ${me?"savedRace":""}`} key={r.source_key}><div className="raceDateBox"><b>{new Date(`${r.race_date}T00:00:00+09:00`).getMonth()+1}/{new Date(`${r.race_date}T00:00:00+09:00`).getDate()}</b><small>{dday(r.race_date)}</small></div><div className="raceLiveBody"><div className="raceLiveTitle"><div><h3>{r.name}</h3><p>{r.region||"지역 미정"} · {r.race_date}</p></div><span className={`raceRegStatus ${r.registration_status}`}>{REG[r.registration_status]||"확인"}</span></div><div className="raceTags">{r.distance_options.map(d=><span className="tag" key={d}>{d}</span>)}{r.registration_start&&<span>접수 {r.registration_start}</span>}{r.registration_deadline&&<span>마감 {r.registration_deadline}</span>}{me&&<span className="tag mine">내 상태 · {STATUS[me.status]||me.status}</span>}</div>{r.registration_text&&<p className="raceRegistrationText">{r.registration_text}</p>}<div className="raceCardActions">{userId?<><button className={me?.status==="interested"?"on":""} disabled={busy===r.source_key} onClick={()=>saveRace(r,"interested")}>관심</button><button className={me?.status==="applied"?"on":""} disabled={busy===r.source_key} onClick={()=>saveRace(r,"applied")}>신청완료</button><button className={me?.status==="going"?"on":""} disabled={busy===r.source_key} onClick={()=>saveRace(r,"going")}>참가예정</button></>:<Link className="raceLoginLink" href="/login">로그인 후 참가 기록</Link>}{r.official_url&&<a href={r.official_url} target="_blank" rel="noreferrer">공식 페이지 ↗</a>}</div>{userId&&me&&r.distance_options.length>0&&<label className="raceDistanceSelect">내 참가 종목<select value={me.distance||""} onChange={e=>saveRace(r,me.status,e.target.value)}><option value="">선택</option>{r.distance_options.map(d=><option key={d}>{d}</option>)}</select></label>}</div></article>})}</div>
  {!loading&&!error&&!filtered.length&&<div className="card emptyState"><b>조건에 맞는 대회가 없어요.</b><p className="muted">검색어나 필터를 바꿔보세요.</p></div>}
  <p className="raceSourceNote">대회 일정·접수 정보는 외부 공개 일정 페이지를 주기적으로 확인해 표시합니다. 실제 일정·접수 여부는 반드시 공식 페이지에서 최종 확인해주세요.</p>
 </div>
}
