"use client";
import {useCallback,useEffect,useMemo,useRef,useState} from "react";
import Link from "next/link";
import {createClient} from "@/lib/supabase/client";

type Pt={lat:number;lng:number;ts?:number;accuracy?:number};
type Props={courseId:string;courseName:string;targetKm:number;routeGeojson:any;startName?:string|null;userId?:string|null;crewId?:string|null};
type RunDraft={version:1;courseId:string;courseName:string;savedAt:number;startedAt:number;elapsed:number;distanceM:number;pausedTotal:number;track:Pt[]};
function haversineM(a:Pt,b:Pt){const R=6371000,toRad=(v:number)=>v*Math.PI/180;const dLat=toRad(b.lat-a.lat),dLng=toRad(b.lng-a.lng);const s=Math.sin(dLat/2)**2+Math.cos(toRad(a.lat))*Math.cos(toRad(b.lat))*Math.sin(dLng/2)**2;return 2*R*Math.asin(Math.sqrt(s));}
function fmtTime(sec:number){const h=Math.floor(sec/3600),m=Math.floor((sec%3600)/60),s=Math.floor(sec%60);return h?`${h}:${String(m).padStart(2,"0")}:${String(s).padStart(2,"0")}`:`${String(m).padStart(2,"0")}:${String(s).padStart(2,"0")}`;}
function fmtPace(sec:number,km:number){if(km<0.05)return "--:--";const p=sec/km,m=Math.floor(p/60),s=Math.floor(p%60);return `${m}:${String(s).padStart(2,"0")}`;}
function pointSegmentDistanceM(p:Pt,a:Pt,b:Pt){const lat0=p.lat*Math.PI/180,scaleX=111320*Math.cos(lat0),scaleY=110540;const px=p.lng*scaleX,py=p.lat*scaleY,ax=a.lng*scaleX,ay=a.lat*scaleY,bx=b.lng*scaleX,by=b.lat*scaleY;const dx=bx-ax,dy=by-ay,len2=dx*dx+dy*dy;if(!len2)return Math.hypot(px-ax,py-ay);const t=Math.max(0,Math.min(1,((px-ax)*dx+(py-ay)*dy)/len2));return Math.hypot(px-(ax+t*dx),py-(ay+t*dy));}
function nearestRouteM(p:Pt,route:Pt[]){if(route.length<2)return route[0]?haversineM(p,route[0]):null;let best=Infinity;for(let i=0;i<route.length-1;i++)best=Math.min(best,pointSegmentDistanceM(p,route[i],route[i+1]));return Number.isFinite(best)?best:null;}

export default function RunMode({courseId,courseName,targetKm,routeGeojson,startName,userId,crewId}:Props){
 const route=useMemo<Pt[]>(()=>((routeGeojson?.coordinates||[]) as any[]).filter(x=>Array.isArray(x)&&x.length>=2).map(x=>({lng:Number(x[0]),lat:Number(x[1])})).filter(p=>Number.isFinite(p.lat)&&Number.isFinite(p.lng)),[routeGeojson]);
 const draftKey=useMemo(()=>`runart:live-run:v1:${userId||"guest"}:${courseId}`,[userId,courseId]);
 const [running,setRunning]=useState(false),[paused,setPaused]=useState(false),[elapsed,setElapsed]=useState(0),[distanceM,setDistanceM]=useState(0),[position,setPosition]=useState<Pt|null>(null),[accuracy,setAccuracy]=useState<number|null>(null),[routeDistance,setRouteDistance]=useState<number|null>(null),[message,setMessage]=useState("GPS 준비 중"),[finished,setFinished]=useState(false),[saving,setSaving]=useState(false),[saveMessage,setSaveMessage]=useState("");
 const [recoverable,setRecoverable]=useState<RunDraft|null>(null),[draftReady,setDraftReady]=useState(false),[lastDraftAt,setLastDraftAt]=useState<number|null>(null);
 const watchRef=useRef<number|null>(null),lastRef=useRef<Pt|null>(null),startedAt=useRef<number|null>(null),pauseStarted=useRef<number|null>(null),pausedTotal=useRef(0),wakeLock=useRef<any>(null),trackRef=useRef<Pt[]>([]);
 const runningRef=useRef(false),pausedRef=useRef(false),finishedRef=useRef(false),distanceRef=useRef(0),elapsedRef=useRef(0);
 useEffect(()=>{runningRef.current=running},[running]);useEffect(()=>{pausedRef.current=paused},[paused]);useEffect(()=>{finishedRef.current=finished},[finished]);useEffect(()=>{distanceRef.current=distanceM},[distanceM]);useEffect(()=>{elapsedRef.current=elapsed},[elapsed]);
 const removeDraft=useCallback(()=>{try{localStorage.removeItem(draftKey)}catch{}setRecoverable(null);setLastDraftAt(null)},[draftKey]);
 const persistDraft=useCallback(()=>{if(!runningRef.current||finishedRef.current||!startedAt.current)return;const draft:RunDraft={version:1,courseId,courseName,savedAt:Date.now(),startedAt:startedAt.current,elapsed:elapsedRef.current,distanceM:distanceRef.current,pausedTotal:pausedTotal.current,track:trackRef.current.slice(-6000)};try{localStorage.setItem(draftKey,JSON.stringify(draft));setLastDraftAt(draft.savedAt)}catch{}},[courseId,courseName,draftKey]);
 useEffect(()=>{try{const raw=localStorage.getItem(draftKey);if(raw){const draft=JSON.parse(raw) as RunDraft;const valid=draft?.version===1&&draft.courseId===courseId&&Date.now()-Number(draft.savedAt||0)<24*60*60*1000&&Number(draft.elapsed||0)>=0&&Number(draft.distanceM||0)>=0;if(valid){setRecoverable(draft);setLastDraftAt(draft.savedAt)}else localStorage.removeItem(draftKey)}}catch{try{localStorage.removeItem(draftKey)}catch{}}finally{setDraftReady(true)}},[draftKey,courseId]);
 useEffect(()=>{let timer:number|undefined;if(running&&!paused&&!finished){timer=window.setInterval(()=>{if(startedAt.current)setElapsed(Math.max(0,Math.floor((Date.now()-startedAt.current-pausedTotal.current)/1000)))},1000)}return()=>{if(timer)clearInterval(timer)}},[running,paused,finished]);
 useEffect(()=>{if(!draftReady||!running||finished)return;const timer=window.setInterval(persistDraft,5000);persistDraft();return()=>window.clearInterval(timer)},[draftReady,running,paused,finished,distanceM,elapsed,persistDraft]);
 useEffect(()=>{const flush=()=>persistDraft();const onVisibility=()=>{if(document.hidden){lastRef.current=null;persistDraft();wakeLock.current?.release?.().catch(()=>{});wakeLock.current=null}else if(runningRef.current&&!finishedRef.current){lastRef.current=null;startGps();requestWakeLock();setMessage(pausedRef.current?"러닝 기록 복귀 · 일시정지 중":"화면 복귀 · GPS 재확인 중")}};window.addEventListener("pagehide",flush);window.addEventListener("beforeunload",flush);document.addEventListener("visibilitychange",onVisibility);return()=>{window.removeEventListener("pagehide",flush);window.removeEventListener("beforeunload",flush);document.removeEventListener("visibilitychange",onVisibility)}},[persistDraft,route]);
 useEffect(()=>()=>{persistDraft();if(watchRef.current!=null)navigator.geolocation.clearWatch(watchRef.current);wakeLock.current?.release?.().catch(()=>{})},[persistDraft]);
 async function requestWakeLock(){try{if(document.visibilityState!=="visible")return;wakeLock.current=await (navigator as any).wakeLock?.request?.("screen")}catch{}}
 function startGps(){if(!navigator.geolocation){setMessage("이 기기에서는 위치 추적을 사용할 수 없습니다.");return}if(watchRef.current!=null)return;watchRef.current=navigator.geolocation.watchPosition(pos=>{const p:Pt={lat:pos.coords.latitude,lng:pos.coords.longitude,ts:Date.now(),accuracy:pos.coords.accuracy};const acc=pos.coords.accuracy;setPosition(p);setAccuracy(acc);setRouteDistance(nearestRouteM(p,route));if(acc>80){setMessage(`GPS 정확도 낮음 ±${Math.round(acc)}m`);lastRef.current=null;return}setMessage("GPS 추적 중");if(runningRef.current&&!pausedRef.current&&!finishedRef.current){if(lastRef.current){const jump=haversineM(lastRef.current,p);if(jump>1&&jump<120){distanceRef.current+=jump;setDistanceM(distanceRef.current);trackRef.current.push(p)}}else trackRef.current.push(p)}lastRef.current=p;},()=>setMessage("위치 권한을 허용해야 러닝 모드를 사용할 수 있습니다."),{enableHighAccuracy:true,maximumAge:1000,timeout:12000});}
 function start(){removeDraft();finishedRef.current=false;runningRef.current=true;pausedRef.current=false;distanceRef.current=0;elapsedRef.current=0;setFinished(false);setDistanceM(0);setElapsed(0);setSaveMessage("");setPosition(null);setAccuracy(null);setRouteDistance(null);pausedTotal.current=0;startedAt.current=Date.now();pauseStarted.current=null;lastRef.current=null;trackRef.current=[];setRunning(true);setPaused(false);setMessage("GPS 연결 중");startGps();requestWakeLock();}
 function restoreDraft(){if(!recoverable)return;const draft=recoverable;const now=Date.now();const safeElapsed=Math.max(0,Math.floor(Number(draft.elapsed||0)));elapsedRef.current=safeElapsed;distanceRef.current=Math.max(0,Number(draft.distanceM||0));trackRef.current=Array.isArray(draft.track)?draft.track:[];startedAt.current=now-safeElapsed*1000;pausedTotal.current=0;pauseStarted.current=now;lastRef.current=null;finishedRef.current=false;runningRef.current=true;pausedRef.current=true;setElapsed(safeElapsed);setDistanceM(distanceRef.current);setFinished(false);setRunning(true);setPaused(true);setPosition(null);setAccuracy(null);setRouteDistance(null);setMessage("복구 완료 · 안전한 곳에서 다시 시작을 눌러주세요.");setRecoverable(null);startGps();requestWakeLock();persistDraft();}
 function discardDraft(){removeDraft();setMessage("이전 임시 러닝 기록을 삭제했습니다.")}
 function togglePause(){if(!runningRef.current||finishedRef.current)return;if(!pausedRef.current){pauseStarted.current=Date.now();pausedRef.current=true;setPaused(true);persistDraft()}else{if(pauseStarted.current)pausedTotal.current+=Date.now()-pauseStarted.current;pauseStarted.current=null;lastRef.current=null;pausedRef.current=false;setPaused(false);setMessage("GPS 재확인 중");startGps();requestWakeLock()}}
 async function saveRun(finalElapsed:number,finalDistanceM:number){if(!userId){setSaveMessage("로그인하지 않아 서버 저장은 생략했습니다. 이 화면을 닫기 전에 결과를 확인해 주세요.");return true}setSaving(true);const sb=createClient();try{const distanceKm=Number((finalDistanceM/1000).toFixed(3));const pace=distanceKm>=0.05?Math.round(finalElapsed/distanceKm):null;const trackGeojson=trackRef.current.length>=2?{type:"LineString",coordinates:trackRef.current.map(p=>[p.lng,p.lat]),properties:{points:trackRef.current.map(p=>({ts:p.ts,accuracy:p.accuracy}))}}:null;const startedIso=new Date(startedAt.current||Date.now()).toISOString();const finishedIso=new Date().toISOString();const {error:liveError}=await sb.from("runart_live_runs").insert({user_id:userId,course_id:courseId,crew_id:crewId||null,started_at:startedIso,finished_at:finishedIso,elapsed_seconds:finalElapsed,distance_km:distanceKm,avg_pace_sec_per_km:pace,track_geojson:trackGeojson});if(liveError)throw liveError;let crewSaved=false;if(crewId){const {data:log,error:logError}=await sb.from("runart_course_logs").insert({crew_id:crewId,course_id:courseId,created_by:userId,run_date:new Date().toISOString().slice(0,10),actual_distance_km:distanceKm,memo:`라이브 러닝 자동 기록 · ${fmtTime(finalElapsed)} · 평균 페이스 ${fmtPace(finalElapsed,distanceKm)}`}).select("id").single();if(!logError&&log?.id){const {error:partError}=await sb.from("runart_log_participants").insert({log_id:log.id,user_id:userId});crewSaved=!partError}}setSaveMessage(crewId?(crewSaved?"GPS 궤적과 크루 러닝 기록까지 자동 저장했습니다.":"GPS 궤적은 저장했습니다. 크루 출석 기록은 권한 설정을 확인해 주세요."):"GPS 궤적을 내 러닝 기록에 저장했습니다.");return true}catch(e:any){setSaveMessage(`${e?.message||"러닝 기록 저장 중 오류가 발생했습니다."} · 임시 기록은 기기에 남겨두었습니다.`);return false}finally{setSaving(false)}}
 async function finish(){if(!runningRef.current)return;persistDraft();if(pauseStarted.current)pausedTotal.current+=Date.now()-pauseStarted.current;const finalElapsed=startedAt.current?Math.floor((Date.now()-startedAt.current-pausedTotal.current)/1000):elapsedRef.current;const finalDistance=distanceRef.current;elapsedRef.current=finalElapsed;setElapsed(finalElapsed);pausedRef.current=false;finishedRef.current=true;runningRef.current=false;setPaused(false);setFinished(true);setRunning(false);if(watchRef.current!=null){navigator.geolocation.clearWatch(watchRef.current);watchRef.current=null}wakeLock.current?.release?.().catch(()=>{});wakeLock.current=null;const saved=await saveRun(finalElapsed,finalDistance);if(saved)removeDraft();}
 const km=distanceM/1000,progress=Math.min(100,targetKm>0?km/targetKm*100:0),offRoute=routeDistance!=null&&route.length>1&&routeDistance>80;
 const gpsState=accuracy==null?"대기":accuracy<=30?"좋음":accuracy<=80?"보통":"낮음";
 const routeStatus=route.length<=1?"🧭 경로선 없음":routeDistance==null?"🧭 위치 확인 중":offRoute?"⚠️ 경로 이탈":"✅ 코스 안쪽";
 const routeStatusText=route.length<=1?"이탈 감지를 지원하지 않는 코스입니다.":routeDistance==null?"GPS 위치를 받은 뒤 코스와의 거리를 계산합니다.":`경로선까지 약 ${Math.round(routeDistance)}m`;
 return <main className="wrap runModePage">
  <header className="runModeTop"><div><span className="eyebrow">LIVE RUN</span><h1>🏃 {courseName}</h1><p>{startName||"코스 출발점"} · 목표 {targetKm.toFixed(1)}km</p></div>{!running?<Link className="btn ghost" href={`/courses/${courseId}`}>← 코스 상세</Link>:<span className="runLivePill">● {paused?"일시정지":"기록 중"}</span>}</header>
  {recoverable&&!running&&!finished&&<section className="card runGuideCard"><b>♻️ 중단된 러닝 기록이 있어요</b><p className="muted">{fmtTime(recoverable.elapsed)} · {(recoverable.distanceM/1000).toFixed(2)}km · GPS {recoverable.track.length}포인트까지 기기에 임시 저장되어 있습니다.</p><div className="actions"><button className="btn" type="button" onClick={restoreDraft}>이어달리기 복구</button><button className="btn ghost" type="button" onClick={discardDraft}>임시 기록 삭제</button></div></section>}
  <section className="runMetricPanel"><div><strong>{km.toFixed(2)}</strong><small>km</small></div><div><strong>{fmtTime(elapsed)}</strong><small>경과시간</small></div><div><strong>{fmtPace(elapsed,km)}</strong><small>분/km</small></div><div className="runProgress"><span style={{width:`${progress}%`}}/><small>목표 대비 {progress.toFixed(0)}%</small></div></section>
  <section className="runStatusGrid"><div className="card runStatusCard"><span className="eyebrow">GPS</span><h3>📍 신호 {gpsState}</h3><p className="muted">{position?`정확도 ${accuracy!=null?`±${Math.round(accuracy)}m`:"확인 중"}`:"러닝 시작 후 위치를 확인합니다."}</p><small className="muted">기록 포인트 {trackRef.current.length}개{lastDraftAt?` · 임시저장 ${new Date(lastDraftAt).toLocaleTimeString("ko-KR",{hour:"2-digit",minute:"2-digit"})}`:""}</small></div><div className={`card runStatusCard ${offRoute?"warning":""}`}><span className="eyebrow">COURSE</span><h3>{routeStatus}</h3><p className="muted">{routeStatusText}</p>{offRoute&&<a className="textLink" href={`/?course=${courseId}#explore`}>지도에서 경로 확인 →</a>}</div></section>
  <section className="card runGuideCard"><b>{finished?"🏁 러닝 완료":paused?"⏸ 일시정지 중":running?"🟢 러닝 진행 중":"출발 준비 완료"}</b><p className="muted">{finished?saveMessage||"기록을 정리하고 있습니다.":paused?message||"안전한 곳에서 다시 시작하세요.":running?message:"GPS 권한을 허용한 뒤 시작 버튼을 눌러주세요."}</p></section>
  {finished&&<section className="section"><div className="card runCompleteCard"><span className="eyebrow">RUN COMPLETE</span><h2>오늘 러닝을 저장했어요</h2><div className="miniStats"><span><b>{km.toFixed(2)}km</b>이동거리</span><span><b>{fmtTime(elapsed)}</b>시간</span><span><b>{fmtPace(elapsed,km)}</b>평균 페이스</span></div><p className="muted">{saving?"러닝 기록 저장 중…":saveMessage}</p><div className="actions"><Link className="btn" href="/my">내 기록 보기</Link><Link className="btn ghost" href={`/courses/${courseId}#after-run`}>🍚 러닝 후 장소</Link><button className="btn ghost" type="button" onClick={start}>↻ 다시 뛰기</button></div></div></section>}
  <div className="runControlDock" aria-label="러닝 컨트롤">{!running&&!finished&&<button className="runPrimaryControl" type="button" onClick={start}>▶ 러닝 시작</button>}{running&&<button className="runPrimaryControl" type="button" onClick={togglePause}>{paused?"▶ 다시 시작":"⏸ 일시정지"}</button>}{running&&<button className="runStopControl" type="button" onClick={finish}>■ 종료</button>}{!running&&finished&&<Link className="runPrimaryControl linkControl" href={`/courses/${courseId}`}>코스 상세로</Link>}<a className="runMapControl" href={`/?course=${courseId}#explore`}>🗺️ 지도</a></div>
  <p className="muted runFootnote">러닝 중 기록은 약 5초마다 이 기기에 임시 저장됩니다. 화면을 다시 열면 이어달리기로 복구할 수 있지만, 모바일 브라우저는 화면 잠금·백그라운드에서 GPS 제공을 중단할 수 있습니다. 안전을 위해 이동 중 화면 조작은 최소화해 주세요.</p>
 </main>;
}
