"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import Link from "next/link";
import {createClient} from "@/lib/supabase/client";

type Pt={lat:number;lng:number;ts?:number;accuracy?:number};
type Props={courseId:string;courseName:string;targetKm:number;routeGeojson:any;startName?:string|null;userId?:string|null;crewId?:string|null};
function haversineM(a:Pt,b:Pt){const R=6371000,toRad=(v:number)=>v*Math.PI/180;const dLat=toRad(b.lat-a.lat),dLng=toRad(b.lng-a.lng);const s=Math.sin(dLat/2)**2+Math.cos(toRad(a.lat))*Math.cos(toRad(b.lat))*Math.sin(dLng/2)**2;return 2*R*Math.asin(Math.sqrt(s));}
function fmtTime(sec:number){const h=Math.floor(sec/3600),m=Math.floor((sec%3600)/60),s=Math.floor(sec%60);return h?`${h}:${String(m).padStart(2,"0")}:${String(s).padStart(2,"0")}`:`${String(m).padStart(2,"0")}:${String(s).padStart(2,"0")}`;}
function fmtPace(sec:number,km:number){if(km<0.05)return "--:--";const p=sec/km,m=Math.floor(p/60),s=Math.floor(p%60);return `${m}:${String(s).padStart(2,"0")}`;}
function pointSegmentDistanceM(p:Pt,a:Pt,b:Pt){const lat0=p.lat*Math.PI/180,scaleX=111320*Math.cos(lat0),scaleY=110540;const px=p.lng*scaleX,py=p.lat*scaleY,ax=a.lng*scaleX,ay=a.lat*scaleY,bx=b.lng*scaleX,by=b.lat*scaleY;const dx=bx-ax,dy=by-ay,len2=dx*dx+dy*dy;if(!len2)return Math.hypot(px-ax,py-ay);const t=Math.max(0,Math.min(1,((px-ax)*dx+(py-ay)*dy)/len2));return Math.hypot(px-(ax+t*dx),py-(ay+t*dy));}
function nearestRouteM(p:Pt,route:Pt[]){if(route.length<2)return route[0]?haversineM(p,route[0]):null;let best=Infinity;for(let i=0;i<route.length-1;i++)best=Math.min(best,pointSegmentDistanceM(p,route[i],route[i+1]));return Number.isFinite(best)?best:null;}

export default function RunMode({courseId,courseName,targetKm,routeGeojson,startName,userId,crewId}:Props){
 const route=useMemo<Pt[]>(()=>((routeGeojson?.coordinates||[]) as any[]).filter(x=>Array.isArray(x)&&x.length>=2).map(x=>({lng:Number(x[0]),lat:Number(x[1])})).filter(p=>Number.isFinite(p.lat)&&Number.isFinite(p.lng)),[routeGeojson]);
 const [running,setRunning]=useState(false),[paused,setPaused]=useState(false),[elapsed,setElapsed]=useState(0),[distanceM,setDistanceM]=useState(0),[position,setPosition]=useState<Pt|null>(null),[accuracy,setAccuracy]=useState<number|null>(null),[routeDistance,setRouteDistance]=useState<number|null>(null),[message,setMessage]=useState("GPS 준비 중"),[finished,setFinished]=useState(false),[saving,setSaving]=useState(false),[saveMessage,setSaveMessage]=useState("");
 const watchRef=useRef<number|null>(null),lastRef=useRef<Pt|null>(null),startedAt=useRef<number|null>(null),pauseStarted=useRef<number|null>(null),pausedTotal=useRef(0),wakeLock=useRef<any>(null),trackRef=useRef<Pt[]>([]);
 useEffect(()=>{let timer:number|undefined;if(running&&!paused&&!finished){timer=window.setInterval(()=>{if(startedAt.current)setElapsed(Math.max(0,Math.floor((Date.now()-startedAt.current-pausedTotal.current)/1000)))},1000)}return()=>{if(timer)clearInterval(timer)}},[running,paused,finished]);
 useEffect(()=>()=>{if(watchRef.current!=null)navigator.geolocation.clearWatch(watchRef.current);wakeLock.current?.release?.().catch(()=>{})},[]);
 async function requestWakeLock(){try{wakeLock.current=await (navigator as any).wakeLock?.request?.("screen")}catch{}}
 function startGps(){if(!navigator.geolocation){setMessage("이 기기에서는 위치 추적을 사용할 수 없습니다.");return}if(watchRef.current!=null)return;watchRef.current=navigator.geolocation.watchPosition(pos=>{const p:Pt={lat:pos.coords.latitude,lng:pos.coords.longitude,ts:Date.now(),accuracy:pos.coords.accuracy};const acc=pos.coords.accuracy;setPosition(p);setAccuracy(acc);setRouteDistance(nearestRouteM(p,route));if(acc>80){setMessage(`GPS 정확도 낮음 ±${Math.round(acc)}m`);return}setMessage("GPS 추적 중");if(running&&!paused&&!finished){if(lastRef.current){const jump=haversineM(lastRef.current,p);if(jump>1&&jump<120){setDistanceM(v=>v+jump);trackRef.current.push(p)}}else trackRef.current.push(p)}lastRef.current=p;},()=>setMessage("위치 권한을 허용해야 러닝 모드를 사용할 수 있습니다."),{enableHighAccuracy:true,maximumAge:2000,timeout:12000});}
 function start(){setFinished(false);setDistanceM(0);setElapsed(0);setSaveMessage("");pausedTotal.current=0;startedAt.current=Date.now();lastRef.current=null;trackRef.current=[];setRunning(true);setPaused(false);startGps();requestWakeLock();}
 function togglePause(){if(!running||finished)return;if(!paused){pauseStarted.current=Date.now();setPaused(true)}else{if(pauseStarted.current)pausedTotal.current+=Date.now()-pauseStarted.current;pauseStarted.current=null;lastRef.current=null;setPaused(false)}}
 async function saveRun(finalElapsed:number,finalDistanceM:number){if(!userId){setSaveMessage("로그인하면 GPS 기록과 크루 러닝 로그를 자동 저장할 수 있습니다.");return}setSaving(true);const sb=createClient();try{const distanceKm=Number((finalDistanceM/1000).toFixed(3));const pace=distanceKm>=0.05?Math.round(finalElapsed/distanceKm):null;const trackGeojson=trackRef.current.length>=2?{type:"LineString",coordinates:trackRef.current.map(p=>[p.lng,p.lat]),properties:{points:trackRef.current.map(p=>({ts:p.ts,accuracy:p.accuracy}))}}:null;const startedIso=new Date(startedAt.current||Date.now()).toISOString();const finishedIso=new Date().toISOString();const {error:liveError}=await sb.from("runart_live_runs").insert({user_id:userId,course_id:courseId,crew_id:crewId||null,started_at:startedIso,finished_at:finishedIso,elapsed_seconds:finalElapsed,distance_km:distanceKm,avg_pace_sec_per_km:pace,track_geojson:trackGeojson});if(liveError)throw liveError;let crewSaved=false;if(crewId){const {data:log,error:logError}=await sb.from("runart_course_logs").insert({crew_id:crewId,course_id:courseId,created_by:userId,run_date:new Date().toISOString().slice(0,10),actual_distance_km:distanceKm,memo:`라이브 러닝 자동 기록 · ${fmtTime(finalElapsed)} · 평균 페이스 ${fmtPace(finalElapsed,distanceKm)}`}).select("id").single();if(!logError&&log?.id){const {error:partError}=await sb.from("runart_log_participants").insert({log_id:log.id,user_id:userId});crewSaved=!partError}}
 setSaveMessage(crewId?(crewSaved?"GPS 궤적과 크루 러닝 기록까지 자동 저장했습니다.":"GPS 궤적은 저장했습니다. 크루 출석 기록은 권한 설정을 확인해 주세요."):"GPS 궤적을 내 러닝 기록에 저장했습니다.");}catch(e:any){setSaveMessage(e?.message||"러닝 기록 저장 중 오류가 발생했습니다.")}finally{setSaving(false)}}
 async function finish(){if(!running)return;if(pauseStarted.current)pausedTotal.current+=Date.now()-pauseStarted.current;const finalElapsed=startedAt.current?Math.floor((Date.now()-startedAt.current-pausedTotal.current)/1000):elapsed;setElapsed(finalElapsed);setPaused(false);setFinished(true);setRunning(false);if(watchRef.current!=null){navigator.geolocation.clearWatch(watchRef.current);watchRef.current=null}wakeLock.current?.release?.().catch(()=>{});await saveRun(finalElapsed,distanceM);}
 const km=distanceM/1000,progress=Math.min(100,targetKm>0?km/targetKm*100:0),offRoute=routeDistance!=null&&route.length>1&&routeDistance>80;
 return <main className="wrap" style={{maxWidth:760,paddingBottom:40}}>
  <header className="top"><div><span className="eyebrow">RUN MODE</span><h2 style={{margin:"4px 0"}}>🏃 {courseName}</h2><p className="muted" style={{margin:0}}>{startName||"코스 출발점"} · 목표 {targetKm.toFixed(1)}km</p></div><Link className="btn ghost" href={`/courses/${courseId}`}>종료하고 상세</Link></header>
  <section className="card" style={{padding:20,position:"sticky",top:8,zIndex:2}}><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:10,textAlign:"center"}}><div><div style={{fontSize:32,fontWeight:900}}>{km.toFixed(2)}</div><small className="muted">km</small></div><div><div style={{fontSize:32,fontWeight:900}}>{fmtTime(elapsed)}</div><small className="muted">경과시간</small></div><div><div style={{fontSize:32,fontWeight:900}}>{fmtPace(elapsed,km)}</div><small className="muted">분/km</small></div></div><div style={{height:10,background:"rgba(0,0,0,.08)",borderRadius:999,marginTop:18,overflow:"hidden"}}><div style={{height:"100%",width:`${progress}%`,background:"currentColor",borderRadius:999}}/></div><p className="muted" style={{margin:"8px 0 0"}}>코스 목표 대비 {progress.toFixed(0)}% · GPS 포인트 {trackRef.current.length}개</p></section>
  <section className="section"><div className="grid2"><div className="card"><span className="eyebrow">LIVE GPS</span><h3>📍 현재 위치</h3>{position?<><p>{position.lat.toFixed(6)}, {position.lng.toFixed(6)}</p><p className="muted">GPS 정확도 {accuracy!=null?`±${Math.round(accuracy)}m`:"확인 중"}</p></>:<p className="muted">러닝 시작 후 위치를 표시합니다.</p>}</div><div className={`card ${offRoute?"warning":""}`}><span className="eyebrow">COURSE CHECK</span><h3>{route.length>1?(offRoute?"⚠️ 코스 이탈 가능":"✅ 코스 안쪽") : "🧭 경로선 없음"}</h3><p className="muted">{route.length>1&&routeDistance!=null?`가장 가까운 경로선까지 약 ${Math.round(routeDistance)}m`:route.length>1?"경로선과 현재 위치를 비교하는 중입니다.":"이 코스는 정확한 경로선이 없어 이탈 감지를 사용할 수 없습니다."}</p>{offRoute&&<a className="btn ghost" href={`/?course=${courseId}#explore`}>RUNART 지도에서 경로 확인</a>}</div></div></section>
  <section className="section"><div className="card" style={{padding:20}}><h3 style={{marginTop:0}}>러닝 컨트롤</h3><p className="muted">{finished?"러닝이 종료되었습니다.":paused?"일시정지 중":running?message:"시작 버튼을 누르면 GPS 기록을 시작합니다."}</p><div className="actions">{!running&&!finished&&<button className="btn" type="button" onClick={start}>▶ 러닝 시작</button>}{running&&<button className="btn" type="button" onClick={togglePause}>{paused?"▶ 다시 시작":"⏸ 일시정지"}</button>}{running&&<button className="btn ghost" type="button" onClick={finish}>■ 러닝 종료</button>}{finished&&<button className="btn" type="button" onClick={start}>↻ 다시 뛰기</button>}<a className="btn ghost" href={`/?course=${courseId}#explore`}>코스 지도 보기</a></div></div></section>
  {finished&&<section className="section"><div className="card" style={{padding:22}}><span className="eyebrow">RUN COMPLETE</span><h2>🏁 러닝 완료</h2><div className="miniStats"><span><b>{km.toFixed(2)}km</b>이동거리</span><span><b>{fmtTime(elapsed)}</b>시간</span><span><b>{fmtPace(elapsed,km)}</b>평균 페이스</span></div><p className="muted">{saving?"러닝 기록 저장 중…":saveMessage}</p><div className="actions" style={{marginTop:16}}><Link className="btn" href={`/courses/${courseId}#after-run`}>🍚 러닝 후 장소 보기</Link><Link className="btn ghost" href="/my">내 기록 보기</Link><Link className="btn ghost" href={`/courses/${courseId}`}>코스 상세로</Link></div></div></section>}
  <p className="muted" style={{fontSize:12}}>GPS 거리는 휴대폰 위치 정확도에 따라 오차가 있을 수 있습니다. 화면을 켜둔 상태에서 사용할 때 가장 안정적입니다.</p>
 </main>;
}
