"use client";
import {useEffect,useMemo,useState} from "react";

type Parking={id:string;name:string;address?:string|null;distance_m?:number|null;walking_minutes?:number|null;source_url?:string|null;latitude?:number|null;longitude?:number|null;public_likely?:boolean;fee_status?:string|null;hours_status?:string|null;weekend_status?:string|null};
type ParkingData={configured:boolean;start?:{lat:number;lng:number}|null;parking:Parking[];note?:string|null};
function distanceLabel(m?:number|null){if(m==null)return "거리 미정";return m<1000?`${m}m`:`${(m/1000).toFixed(1)}km`;}
function kakaoToParking(p:Parking){return p.latitude!=null&&p.longitude!=null?`https://map.kakao.com/link/to/${encodeURIComponent(p.name)},${p.latitude},${p.longitude}`:(p.source_url||"#");}
function kakaoToStart(start:{lat:number;lng:number},name:string){return `https://map.kakao.com/link/to/${encodeURIComponent(name)},${start.lat},${start.lng}`;}
function kakaoWalk(start:{lat:number;lng:number},p:Parking){return `https://map.kakao.com/link/from/${encodeURIComponent(p.name)},${p.latitude},${p.longitude}/to/${encodeURIComponent("러닝 출발점")},${start.lat},${start.lng}`;}
function naverSearch(p:Parking){return `https://map.naver.com/p/search/${encodeURIComponent(p.name+(p.address?` ${p.address}`:""))}`;}
function openNaverCar(p:Parking){if(p.latitude==null||p.longitude==null)return window.open(naverSearch(p),"_blank");const scheme=`nmap://route/car?dlat=${p.latitude}&dlng=${p.longitude}&dname=${encodeURIComponent(p.name)}&appname=com.ttwittun.korea`;const fallback=naverSearch(p);const mobile=/Android|iPhone|iPad|iPod/i.test(navigator.userAgent);if(!mobile)return window.open(fallback,"_blank");window.location.href=scheme;setTimeout(()=>{if(!document.hidden)window.location.href=fallback},1200);}
function openNaverStart(start:{lat:number;lng:number},name:string){const scheme=`nmap://route/walk?dlat=${start.lat}&dlng=${start.lng}&dname=${encodeURIComponent(name)}&appname=com.ttwittun.korea`;const fallback=`https://map.naver.com/p/search/${encodeURIComponent(name)}?c=${start.lng},${start.lat},16,0,0,0,dh`;const mobile=/Android|iPhone|iPad|iPod/i.test(navigator.userAgent);if(!mobile)return window.open(fallback,"_blank");window.location.href=scheme;setTimeout(()=>{if(!document.hidden)window.location.href=fallback},1200);}
function openNaverWalk(start:{lat:number;lng:number},p:Parking){if(p.latitude==null||p.longitude==null)return;const scheme=`nmap://route/walk?slat=${p.latitude}&slng=${p.longitude}&sname=${encodeURIComponent(p.name)}&dlat=${start.lat}&dlng=${start.lng}&dname=${encodeURIComponent("러닝 출발점")}&appname=com.ttwittun.korea`;const fallback=`https://map.naver.com/p/search/${encodeURIComponent("러닝 출발점")}?c=${start.lng},${start.lat},16,0,0,0,dh`;const mobile=/Android|iPhone|iPad|iPod/i.test(navigator.userAgent);if(!mobile)return window.open(fallback,"_blank");window.location.href=scheme;setTimeout(()=>{if(!document.hidden)window.location.href=fallback},1200);}

export default function RunStartFlow({courseId,courseName,startName}:{courseId:string;courseName:string;startName?:string|null}){
 const [data,setData]=useState<ParkingData|null>(null);const [selectedId,setSelectedId]=useState<string>("");
 useEffect(()=>{let cancelled=false;fetch(`/api/parking/nearby?courseId=${encodeURIComponent(courseId)}`,{cache:"no-store"}).then(r=>r.json()).then(d=>{if(cancelled)return;setData(d);if(d.parking?.[0]?.id)setSelectedId(d.parking[0].id)}).catch(()=>{if(!cancelled)setData({configured:false,parking:[]})});return()=>{cancelled=true}},[courseId]);
 const selected=useMemo(()=>data?.parking?.find(p=>p.id===selectedId)||data?.parking?.[0]||null,[data,selectedId]);const canWalk=!!(data?.start&&selected?.latitude!=null&&selected?.longitude!=null);const startLabel=startName||`${courseName} 출발점`;
 return <section className="section startFlowCompact" id="run-start">
  <div className="card startFlowCard">
   <div className="startFlowHead"><div><span className="eyebrow">TTWITTUN READY</span><h2>🏁 출발 준비</h2><p className="muted">주차 → 출발점 → 라이브 러닝, 필요한 것만 순서대로 확인하세요.</p></div><a className="btn startNowBtn" href={`/run/${courseId}`}>🏃 바로 러닝 시작</a></div>
   <div className="startProgress" aria-label="출발 준비 단계"><span className="done"><b>1</b>코스 선택</span><span className="active"><b>2</b>출발 준비</span><span><b>3</b>라이브 러닝</span><span><b>4</b>개인 기록</span></div>
   {!data?<div className="startFlowLoading">출발 준비 정보를 불러오는 중...</div>:<div className="startFlowBody">
    <div className="startFlowStep"><div className="startStepNo">1</div><div className="startStepContent"><div className="startStepTitle"><div><h3>🚗 주차장으로 이동</h3><p className="muted">차량 이용 시 추천 주차장을 하나만 고르면 됩니다.</p></div>{!!data.parking?.length&&<select aria-label="추천 주차장 선택" value={selected?.id||""} onChange={e=>setSelectedId(e.target.value)}>{data.parking.map(p=><option key={p.id} value={p.id}>{p.name} · {distanceLabel(p.distance_m)}{p.walking_minutes?` · 도보 ${p.walking_minutes}분`:""}</option>)}</select>}</div>
      {selected?<div className="selectedParking"><div><b>{selected.name}</b><span>{selected.address||"주소 정보 없음"}</span><small>{distanceLabel(selected.distance_m)} · 도보 약 {selected.walking_minutes||"-"}분 · {selected.fee_status||"요금 확인 필요"}</small></div><div className="compactActions"><a className="btn" href={kakaoToParking(selected)} target="_blank" rel="noreferrer">카카오</a><button className="btn ghost" type="button" onClick={()=>openNaverCar(selected)}>네이버</button></div></div>:<p className="muted startEmptyNote">추천 주차장이 없어요. 차량을 이용하지 않는다면 바로 2단계로 진행하세요.</p>}
     </div></div>
    <div className="startFlowStep"><div className="startStepNo">2</div><div className="startStepContent"><div className="startStepTitle"><div><h3>🚶 출발점 도착</h3><p className="muted">{startLabel}{selected?.walking_minutes?` · 주차장에서 도보 약 ${selected.walking_minutes}분`:""}</p></div></div>{data.start?<><div className="compactActions"><a className="btn" href={kakaoToStart(data.start,startLabel)} target="_blank" rel="noreferrer">카카오 출발점</a><button className="btn ghost" type="button" onClick={()=>openNaverStart(data.start!,startLabel)}>네이버 출발점</button></div>{canWalk&&<div className="compactActions"><a className="btn ghost" href={kakaoWalk(data.start,selected!)} target="_blank" rel="noreferrer">주차 → 출발 도보</a><button className="btn ghost" type="button" onClick={()=>openNaverWalk(data.start!,selected!)}>네이버 도보</button></div>}</>:<a className="textLink" href={`/?course=${courseId}#explore`}>출발점 지도 확인 →</a>}</div></div>
    <div className="startFlowStep startFlowFinal"><div className="startStepNo">3</div><div className="startStepContent"><div className="startStepTitle"><div><h3>🏃 러닝 시작</h3><p className="muted">거리·시간·현재/평균 페이스·1km 자동랩·GPS 위치와 코스 이탈 여부를 실시간으로 확인합니다.</p></div></div><div className="compactActions"><a className="btn runPrimary" href={`/run/${courseId}`}>라이브 러닝 시작</a><a className="btn ghost" href={`/?course=${courseId}#explore`}>코스 지도</a></div></div></div>
    <div className="afterRunHint"><span>완주 후에는 개인 기록이 MY에 저장되고,</span><a href="#after-run">🍚 주변 맛집·카페도 이어서 볼 수 있어요 →</a></div>
   </div>}
  </div>
 </section>;
}
