import {NextResponse} from "next/server";
import {createHash} from "crypto";

const RUNG_URL="https://rung.kr/";
const KIMRUN_URL="https://kimrunning.com/marathon";
const REGIONS=["서울","부산","대구","인천","광주","대전","울산","세종","경기","강원","충북","충남","전북","전남","경북","경남","제주","충청","경상","전라"];

type Race={source_key:string;name:string;race_date:string;region:string|null;distance_options:string[];registration_start:string|null;registration_deadline:string|null;registration_status:string;official_url:string|null;registration_url?:string|null;registration_text?:string|null;source_name:string;source_url:string;source_kind?:"aggregator"|"official"|"google_form"};

function decode(s:string){return s.replace(/&nbsp;/g," ").replace(/&amp;/g,"&").replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,"<").replace(/&gt;/g,">")}
function textOf(html:string){return decode(html.replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim())}
function isoDate(raw:string){const dot=raw.match(/(20\d{2})\s*[.\/-]\s*(\d{1,2})\s*[.\/-]\s*(\d{1,2})/),kor=raw.match(/(20\d{2})\s*년\s*(\d{1,2})\s*월\s*(\d{1,2})\s*일/),short=raw.match(/(?:^|\s)(\d{2})[.\/-](\d{1,2})[.\/-](\d{1,2})(?:\s|$)/);const m=dot||kor;if(m)return `${m[1]}-${m[2].padStart(2,"0")}-${m[3].padStart(2,"0")}`;if(short)return `20${short[1]}-${short[2].padStart(2,"0")}-${short[3].padStart(2,"0")}`;return null}
function allDates(raw:string){const found:string[]=[];const re=/(20\d{2}\s*(?:[.\/-]\s*\d{1,2}\s*[.\/-]\s*\d{1,2}|년\s*\d{1,2}\s*월\s*\d{1,2}\s*일)|\b\d{2}[.\/-]\d{1,2}[.\/-]\d{1,2}\b)/g;let m:RegExpExecArray|null;while((m=re.exec(raw))){const d=isoDate(m[1]);if(d)found.push(d)}return found}
function distances(t:string){const out:string[]=[];if(/풀|full/i.test(t))out.push("Full");if(/하프|half/i.test(t))out.push("Half");for(const m of t.matchAll(/(?:^|\D)(\d+(?:\.\d+)?)\s*(?:km|k)\b/gi)){const n=Number(m[1]);if(n===5)out.push("5K");else if(n===10)out.push("10K");else if(n>0)out.push(`${n}K`)}if(/울트라|ultra/i.test(t))out.push("Ultra");return Array.from(new Set(out))}
function regionOf(t:string){return REGIONS.find(x=>new RegExp(`(^|\\s|[·|])${x}(\\s|$|[·|])`).test(t))||null}
function registrationWindow(t:string,eventDate:string){const idx=t.indexOf("접수");if(idx<0)return {start:null,deadline:null};const dates=allDates(t.slice(idx)).filter(d=>d!==eventDate);if(dates.length>=2)return {start:dates[0],deadline:dates[1]};if(dates.length===1)return {start:null,deadline:dates[0]};return {start:null,deadline:null}}
function statusOf(t:string,start:string|null,deadline:string|null){const now=new Date(),today=new Date(now.getFullYear(),now.getMonth(),now.getDate()).getTime();if(/접수\s*마감|접수종료|접수완료/.test(t))return "closed";if(start&&new Date(`${start}T00:00:00+09:00`).getTime()>today)return "upcoming";if(deadline&&new Date(`${deadline}T23:59:59+09:00`).getTime()<today)return "closed";if(/접수중|접수 시작|접수기간|신청/.test(t)&&deadline)return "open";return "unknown"}
function googleFormUrl(raw:string){const m=raw.match(/https?:\/\/(?:forms\.gle\/[A-Za-z0-9_-]+|docs\.google\.com\/forms\/[^\s"'<>]+)/i);return m?.[0]?.replace(/&amp;/g,"&")||null}
function cleanName(t:string,date:string){let name=t.split(date.replace(/-/g,"."))[0]||t;name=name.replace(/D[-+]?\d+/gi," ").replace(/오늘|NEW|접수중|접수마감|접수종료|접수전|접수미정/g," ").replace(/공식 사이트\s*→?/g," ").replace(/\s+/g," ").trim();return name}
function normalizedName(s:string){return s.toLowerCase().replace(/20\d{2}/g,"").replace(/제\s*\d+\s*회/g,"").replace(/[\s·ㆍ\-_/()[\]{}:]/g,"").replace(/마라톤대회/g,"마라톤")}
function score(r:Race){return (r.official_url?3:0)+(r.registration_url?4:0)+(r.registration_deadline?2:0)+(r.registration_start?1:0)+r.distance_options.length+(r.region?1:0)}
function dedupe(rows:Race[]){const map=new Map<string,Race>();for(const r of rows){const key=`${normalizedName(r.name)}|${r.race_date}`;const prev=map.get(key);if(!prev||score(r)>score(prev))map.set(key,{...(prev||{}),...r,distance_options:Array.from(new Set([...(prev?.distance_options||[]),...r.distance_options])),registration_url:r.registration_url||prev?.registration_url||null,official_url:r.official_url||prev?.official_url||null});else if(prev){prev.distance_options=Array.from(new Set([...prev.distance_options,...r.distance_options]));prev.registration_url=prev.registration_url||r.registration_url||null;prev.official_url=prev.official_url||r.official_url||null}}return Array.from(map.values())}
async function fetchText(url:string){const r=await fetch(url,{headers:{"user-agent":"TTWITTUN-RaceIndex/1.3 (+https://runart-korea.vercel.app)"},next:{revalidate:1800}});if(!r.ok)throw new Error(`${url} ${r.status}`);return r.text()}

async function rungRows():Promise<Race[]>{const html=await fetchText(RUNG_URL),rows:Race[]=[];const re=/<a\b([^>]*)href=["']([^"']+)["']([^>]*)>([\s\S]*?)<\/a>/gi;let m:RegExpExecArray|null;while((m=re.exec(html))){const txt=textOf(m[4]),eventDates=allDates(txt),date=eventDates[0]||null;if(!date)continue;const name=cleanName(txt,date);if(name.length<4||/^전체$/.test(name))continue;if(new Date(`${date}T23:59:59+09:00`).getTime()<Date.now()-86400000)continue;const official=m[2].startsWith("http")?m[2]:new URL(m[2],RUNG_URL).toString(),window=registrationWindow(txt,date),form=googleFormUrl(`${m[4]} ${txt}`),key=createHash("sha1").update(`${normalizedName(name)}|${date}`).digest("hex").slice(0,20);rows.push({source_key:`race:${key}`,name,race_date:date,region:regionOf(txt),distance_options:distances(txt),registration_start:window.start,registration_deadline:window.deadline,registration_status:statusOf(txt,window.start,window.deadline),official_url:official,registration_url:form,registration_text:(txt.includes("접수")?txt.slice(txt.indexOf("접수")):"").slice(0,180),source_name:"rung",source_url:RUNG_URL,source_kind:form?"google_form":"aggregator"})}return rows}

async function kimRunningRows():Promise<Race[]>{const html=await fetchText(KIMRUN_URL),rows:Race[]=[];const linkRe=/<a\b[^>]*href=["']([^"']*\/marathon\/\d+[^"']*)["'][^>]*>([\s\S]*?)<\/a>/gi;let m:RegExpExecArray|null;const seen=new Set<string>();while((m=linkRe.exec(html))){const href=m[1].startsWith("http")?m[1]:new URL(m[1],KIMRUN_URL).toString();if(seen.has(href))continue;seen.add(href);const idx=m.index,near=html.slice(Math.max(0,idx-1500),Math.min(html.length,idx+3500)),txt=textOf(near),date=allDates(txt).find(d=>new Date(`${d}T23:59:59+09:00`).getTime()>=Date.now()-86400000);if(!date)continue;let name=textOf(m[2]).replace(/자세히/g,"").trim();if(name.length<4){const h=near.match(/<h[23][^>]*>([\s\S]*?)<\/h[23]>/i);name=h?textOf(h[1]):""}if(name.length<4)continue;const window=registrationWindow(txt,date),form=googleFormUrl(near),key=createHash("sha1").update(`${normalizedName(name)}|${date}`).digest("hex").slice(0,20);rows.push({source_key:`race:${key}`,name,race_date:date,region:regionOf(txt),distance_options:distances(txt),registration_start:window.start,registration_deadline:window.deadline,registration_status:statusOf(txt,window.start,window.deadline),official_url:href,registration_url:form,registration_text:(txt.match(/접수기간[^]{0,140}/)?.[0]||"").slice(0,180),source_name:"kimrunning",source_url:KIMRUN_URL,source_kind:form?"google_form":"aggregator"})}return rows}

export async function GET(){const errors:string[]=[];const groups=await Promise.all([rungRows().catch(e=>{errors.push(`rung: ${e?.message||e}`);return []}),kimRunningRows().catch(e=>{errors.push(`kimrunning: ${e?.message||e}`);return []})]);const races=dedupe(groups.flat()).sort((a,b)=>a.race_date.localeCompare(b.race_date)).slice(0,240),formCount=races.filter(r=>!!r.registration_url).length;return NextResponse.json({races,sources:[{name:"rung",url:RUNG_URL},{name:"kimrunning",url:KIMRUN_URL}],count:races.length,google_form_count:formCount,partial_errors:errors,fetched_at:new Date().toISOString()},{status:races.length?200:502})}
