import {NextResponse} from "next/server";
import {createHash} from "crypto";
import {createClient} from "@/lib/supabase/server";

const RUNG_URL="https://rung.kr/";
const KIMRUN_URL="https://kimrunning.com/marathon";
const RUNFOR_URL="https://runfor.kr/";
const MARATHON_MOA_URL="https://marathon.me.kr/events";
const REGIONS=["서울","부산","대구","인천","광주","대전","울산","세종","경기","강원","충북","충남","전북","전남","경북","경남","제주","충청","경상","전라"];

type Race={source_key:string;name:string;race_date:string;region:string|null;distance_options:string[];registration_start:string|null;registration_deadline:string|null;registration_status:string;official_url:string|null;registration_url?:string|null;registration_text?:string|null;source_name:string;source_url:string;source_kind?:"aggregator"|"official"|"google_form"|"community"};

function decode(s:string){return s.replace(/&nbsp;/g," ").replace(/&amp;/g,"&").replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,"<").replace(/&gt;/g,">")}
function textOf(html:string){return decode(html.replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim())}
function isoDate(raw:string){const dot=raw.match(/(20\d{2})\s*[.\/-]\s*(\d{1,2})\s*[.\/-]\s*(\d{1,2})/),kor=raw.match(/(20\d{2})\s*년\s*(\d{1,2})\s*월\s*(\d{1,2})\s*일/),short=raw.match(/(?:^|\s)(\d{2})[.\/-](\d{1,2})[.\/-](\d{1,2})(?:\s|$)/);const m=dot||kor;if(m)return `${m[1]}-${m[2].padStart(2,"0")}-${m[3].padStart(2,"0")}`;if(short)return `20${short[1]}-${short[2].padStart(2,"0")}-${short[3].padStart(2,"0")}`;return null}
function allDates(raw:string){const found:string[]=[];const re=/(20\d{2}\s*(?:[.\/-]\s*\d{1,2}\s*[.\/-]\s*\d{1,2}|년\s*\d{1,2}\s*월\s*\d{1,2}\s*일)|\b\d{2}[.\/-]\d{1,2}[.\/-]\d{1,2}\b)/g;let m:RegExpExecArray|null;while((m=re.exec(raw))){const d=isoDate(m[1]);if(d)found.push(d)}return found}
function distances(t:string){const out:string[]=[];if(/풀|full/i.test(t))out.push("Full");if(/하프|half/i.test(t))out.push("Half");for(const m of t.matchAll(/(?:^|\D)(\d+(?:\.\d+)?)\s*(?:km|k)\b/gi)){const n=Number(m[1]);if(n===5)out.push("5K");else if(n===10)out.push("10K");else if(n>0&&n<=200)out.push(`${n}K`)}if(/울트라|ultra/i.test(t))out.push("Ultra");return Array.from(new Set(out))}
function regionOf(t:string){return REGIONS.find(x=>new RegExp(`(^|\\s|[·|])${x}(\\s|$|[·|])`).test(t))||null}
function registrationWindow(t:string,eventDate:string){const idx=t.search(/접수|신청/);if(idx<0)return {start:null,deadline:null};const dates=allDates(t.slice(idx)).filter(d=>d!==eventDate);if(dates.length>=2)return {start:dates[0],deadline:dates[1]};if(dates.length===1)return {start:null,deadline:dates[0]};return {start:null,deadline:null}}
function statusOf(t:string,start:string|null,deadline:string|null){const now=new Date(),today=new Date(now.getFullYear(),now.getMonth(),now.getDate()).getTime();if(/접수\s*마감|접수종료|접수완료|신청마감/.test(t))return "closed";if(start&&new Date(`${start}T00:00:00+09:00`).getTime()>today)return "upcoming";if(deadline&&new Date(`${deadline}T23:59:59+09:00`).getTime()<today)return "closed";if(/접수중|접수 시작|접수기간|신청/.test(t)&&(deadline||/접수중/.test(t)))return "open";return "unknown"}
function googleFormUrl(raw:string){const m=raw.match(/https?:\/\/(?:forms\.gle\/[A-Za-z0-9_-]+|docs\.google\.com\/forms\/[^\s"'<>]+)/i);return m?.[0]?.replace(/&amp;/g,"&")||null}
function cleanName(t:string,date:string){let name=t.split(date.replace(/-/g,"."))[0]||t;name=name.replace(/D[-+]?\d+/gi," ").replace(/오늘|NEW|접수중|접수마감|접수종료|접수전|접수미정/g," ").replace(/공식 사이트\s*→?/g," ").replace(/\s+/g," ").trim();return name}
function normalizedName(s:string){return s.toLowerCase().replace(/20\d{2}/g,"").replace(/제\s*\d+\s*회/g,"").replace(/[\s·ㆍ\-_/()[\]{}:]/g,"").replace(/마라톤대회/g,"마라톤")}
function looksLikeRace(s:string){return /(마라톤|러닝|런\b|run\b|레이스|race|트레일|trail|울트라|걷기대회)/i.test(s)}
function score(r:Race){return (r.official_url?3:0)+(r.registration_url?5:0)+(r.registration_deadline?2:0)+(r.registration_start?1:0)+r.distance_options.length+(r.region?1:0)+(r.source_kind==="community"?2:0)}
function dedupe(rows:Race[]){const map=new Map<string,Race>();for(const r of rows){const key=`${normalizedName(r.name)}|${r.race_date}`;const prev=map.get(key);if(!prev||score(r)>score(prev))map.set(key,{...(prev||{}),...r,distance_options:Array.from(new Set([...(prev?.distance_options||[]),...r.distance_options])),registration_url:r.registration_url||prev?.registration_url||null,official_url:r.official_url||prev?.official_url||null});else if(prev){prev.distance_options=Array.from(new Set([...prev.distance_options,...r.distance_options]));prev.registration_url=prev.registration_url||r.registration_url||null;prev.official_url=prev.official_url||r.official_url||null}}return Array.from(map.values())}
async function fetchText(url:string){const r=await fetch(url,{headers:{"user-agent":"TTWITTUN-RaceIndex/1.4 (+https://runart-korea.vercel.app)"},next:{revalidate:1800}});if(!r.ok)throw new Error(`${url} ${r.status}`);return r.text()}
function raceKey(name:string,date:string){return `race:${createHash("sha1").update(`${normalizedName(name)}|${date}`).digest("hex").slice(0,20)}`}

async function rungRows():Promise<Race[]>{const html=await fetchText(RUNG_URL),rows:Race[]=[];const re=/<a\b([^>]*)href=["']([^"']+)["']([^>]*)>([\s\S]*?)<\/a>/gi;let m:RegExpExecArray|null;while((m=re.exec(html))){const txt=textOf(m[4]),date=allDates(txt)[0]||null;if(!date)continue;const name=cleanName(txt,date);if(name.length<4||!looksLikeRace(name))continue;if(new Date(`${date}T23:59:59+09:00`).getTime()<Date.now()-86400000)continue;const official=m[2].startsWith("http")?m[2]:new URL(m[2],RUNG_URL).toString(),window=registrationWindow(txt,date),form=googleFormUrl(`${m[4]} ${txt}`);rows.push({source_key:raceKey(name,date),name,race_date:date,region:regionOf(txt),distance_options:distances(txt),registration_start:window.start,registration_deadline:window.deadline,registration_status:statusOf(txt,window.start,window.deadline),official_url:official,registration_url:form,registration_text:(txt.match(/(?:접수|신청)[\s\S]{0,180}/)?.[0]||"").slice(0,180),source_name:"rung",source_url:RUNG_URL,source_kind:form?"google_form":"aggregator"})}return rows}

async function kimRunningRows():Promise<Race[]>{const html=await fetchText(KIMRUN_URL),rows:Race[]=[];const linkRe=/<a\b[^>]*href=["']([^"']*\/marathon\/\d+[^"']*)["'][^>]*>([\s\S]*?)<\/a>/gi;let m:RegExpExecArray|null;const seen=new Set<string>();while((m=linkRe.exec(html))){const href=m[1].startsWith("http")?m[1]:new URL(m[1],KIMRUN_URL).toString();if(seen.has(href))continue;seen.add(href);const idx=m.index,cardStart=html.lastIndexOf("<li",idx),cardEnd=html.indexOf("</li>",idx);if(cardStart<0||cardEnd<0)continue;const card=html.slice(cardStart,cardEnd+5),txt=textOf(card),date=allDates(txt).find(d=>new Date(`${d}T23:59:59+09:00`).getTime()>=Date.now()-86400000);if(!date)continue;const name=textOf(m[2]).replace(/자세히/g,"").trim();if(name.length<4||!looksLikeRace(name))continue;const window=registrationWindow(txt,date),form=googleFormUrl(card);rows.push({source_key:raceKey(name,date),name,race_date:date,region:regionOf(txt),distance_options:distances(txt),registration_start:window.start,registration_deadline:window.deadline,registration_status:statusOf(txt,window.start,window.deadline),official_url:href,registration_url:form,registration_text:(txt.match(/(?:접수|신청)[\s\S]{0,180}/)?.[0]||"").slice(0,180),source_name:"kimrunning",source_url:KIMRUN_URL,source_kind:form?"google_form":"aggregator"})}return rows}

async function genericAggregatorRows(url:string,sourceName:string):Promise<Race[]>{const html=await fetchText(url),rows:Race[]=[];const re=/<a\b[^>]*href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi;let m:RegExpExecArray|null;const seen=new Set<string>();while((m=re.exec(html))){const anchor=textOf(m[2]);if(anchor.length<4||!looksLikeRace(anchor))continue;const idx=m.index,near=html.slice(Math.max(0,idx-900),Math.min(html.length,idx+2200)),txt=textOf(near),date=allDates(txt).find(d=>new Date(`${d}T23:59:59+09:00`).getTime()>=Date.now()-86400000);if(!date)continue;const name=anchor.replace(/자세히|상세 보기|공식 접수 확인|길찾기/g,"").trim();if(name.length<4||!looksLikeRace(name))continue;const dedupeKey=`${normalizedName(name)}|${date}`;if(seen.has(dedupeKey))continue;seen.add(dedupeKey);const href=m[1].startsWith("http")?m[1]:new URL(m[1],url).toString(),window=registrationWindow(txt,date),form=googleFormUrl(near);rows.push({source_key:raceKey(name,date),name,race_date:date,region:regionOf(txt),distance_options:distances(txt),registration_start:window.start,registration_deadline:window.deadline,registration_status:statusOf(txt,window.start,window.deadline),official_url:href,registration_url:form,registration_text:(txt.match(/(?:접수|신청)[\s\S]{0,180}/)?.[0]||"").slice(0,180),source_name:sourceName,source_url:url,source_kind:form?"google_form":"aggregator"})}return rows}

async function approvedSubmissionRows():Promise<Race[]>{try{const sb=await createClient();const today=new Date(Date.now()-86400000).toISOString().slice(0,10);const {data,error}=await sb.from("runart_public_race_submissions").select("id,race_name,race_date,region,source_url,note").eq("status","approved").gte("race_date",today).order("race_date",{ascending:true});if(error)throw error;return (data||[]).filter((x:any)=>x.race_name&&x.race_date&&x.source_url).map((x:any)=>{const form=googleFormUrl(x.source_url)||googleFormUrl(x.note||"");const txt=`${x.race_name||""} ${x.note||""}`;return {source_key:raceKey(x.race_name,x.race_date),name:x.race_name,race_date:x.race_date,region:x.region||regionOf(txt),distance_options:distances(txt),registration_start:null,registration_deadline:null,registration_status:"unknown",official_url:x.source_url,registration_url:form,registration_text:(x.note||"").slice(0,180),source_name:"community",source_url:x.source_url,source_kind:form?"google_form":"community"} as Race})}catch{return []}}

export async function GET(){const errors:string[]=[];const tasks=[rungRows().catch(e=>{errors.push(`rung: ${e?.message||e}`);return []}),kimRunningRows().catch(e=>{errors.push(`kimrunning: ${e?.message||e}`);return []}),genericAggregatorRows(RUNFOR_URL,"runfor").catch(e=>{errors.push(`runfor: ${e?.message||e}`);return []}),genericAggregatorRows(MARATHON_MOA_URL,"marathonmoa").catch(e=>{errors.push(`marathonmoa: ${e?.message||e}`);return []}),approvedSubmissionRows()];const groups=await Promise.all(tasks);const races=dedupe(groups.flat()).sort((a,b)=>a.race_date.localeCompare(b.race_date)).slice(0,400),formCount=races.filter(r=>!!r.registration_url).length;return NextResponse.json({races,sources:[{name:"rung",url:RUNG_URL},{name:"kimrunning",url:KIMRUN_URL},{name:"runfor",url:RUNFOR_URL},{name:"marathonmoa",url:MARATHON_MOA_URL},{name:"community",url:"/races/submit"}],count:races.length,google_form_count:formCount,partial_errors:errors,fetched_at:new Date().toISOString()},{status:races.length?200:502})}
