import Link from "next/link";
import {redirect} from "next/navigation";
import Brand from "@/components/Brand";
import LogoutButton from "@/components/LogoutButton";
import {createClient} from "@/lib/supabase/server";

export default async function Dashboard(){
 const sb=await createClient();const {data:{user}}=await sb.auth.getUser();if(!user)redirect("/login");
 const {data:owned}=await sb.from("runart_crews").select("id,name").eq("owner_id",user.id).maybeSingle();const {data:memberships}=await sb.from("runart_crew_members").select("crew_id,role").eq("user_id",user.id);const membership=memberships?.[0],crewId=owned?.id||membership?.crew_id,role=owned?"owner":membership?.role||"member";if(!crewId)redirect("/join");const canManage=["owner","admin"].includes(role);
 const {data:memberRows}=await sb.from("runart_crew_members").select("user_id").eq("crew_id",crewId);const memberIds=(memberRows||[]).map((m:any)=>m.user_id);const {data:profiles}=memberIds.length?await sb.from("runart_profiles").select("user_id,display_name").in("user_id",memberIds):{data:[] as any[]};const names=new Map((profiles||[]).map((p:any)=>[p.user_id,p.display_name]));const myName=names.get(user.id)||user.email?.split("@")[0]||"러너";
 const {data:logs}=await sb.from("runart_course_logs").select("id,run_date,actual_distance_km,course_id,runart_courses(distance_km)").eq("crew_id",crewId).order("run_date",{ascending:false}).limit(150);const logIds=(logs||[]).map((l:any)=>l.id);const {data:parts}=logIds.length?await sb.from("runart_log_participants").select("log_id,user_id").in("log_id",logIds):{data:[] as any[]};const myLogIds=new Set((parts||[]).filter((p:any)=>p.user_id===user.id).map((p:any)=>p.log_id));const myLogs=(logs||[]).filter((l:any)=>myLogIds.has(l.id)),myKm=myLogs.reduce((s:number,l:any)=>s+Number(l.actual_distance_km||l.runart_courses?.distance_km||0),0),myDone=new Set(myLogs.map((l:any)=>l.course_id));
 return <main className="wrap hubPage crewHubPage"><header className="top compactPageTop"><Brand/><div className="nav"><Link className="btn ghost" href="/my">MY</Link><LogoutButton/></div></header><section className="compactPageHero"><span className="eyebrow">CREW</span><h1>{owned?.name||"러닝 크루"}</h1><p className="muted">{myName} · {role} · 크루원 {(memberRows||[]).length}명</p></section><section className="myHubSummary"><div><small>내 참여</small><b>{myLogs.length}<em>회</em></b></div><div><small>완주 코스</small><b>{myDone.size}<em>개</em></b></div><div><small>내 거리</small><b>{myKm.toFixed(1)}<em>km</em></b></div><div><small>크루 기록</small><b>{(logs||[]).length}<em>회</em></b></div></section><section className="pageHubGrid"><Link className="hubTile primaryHubTile" href="/dashboard/add"><span>＋</span><div><small>ADD RUN</small><h2>기록 추가</h2><p>참가자와 실제 거리 입력</p></div><b>›</b></Link><Link className="hubTile" href="/dashboard/activity"><span>👟</span><div><small>ACTIVITY</small><h2>최근 러닝</h2><p>크루 활동·참여 현황</p></div><b>›</b></Link><Link className="hubTile" href="/dashboard/completed"><span>✓</span><div><small>COMPLETED</small><h2>완주 코스</h2><p>내가 참여한 크루런 코스</p></div><b>›</b></Link><Link className="hubTile" href="/races"><span>🏁</span><div><small>RACE</small><h2>대회</h2><p>참가 일정과 현황</p></div><b>›</b></Link>{canManage&&<Link className="hubTile" href="/manage"><span>⚙</span><div><small>ADMIN</small><h2>크루 관리</h2><p>멤버·신청·코스 승인</p></div><b>›</b></Link>}<Link className="hubTile" href="/explore"><span>⌕</span><div><small>COURSE</small><h2>코스 찾기</h2><p>다음 크루런 코스 탐색</p></div><b>›</b></Link><Link className="hubTile" href="/my/history"><span>●</span><div><small>MY RUN</small><h2>내 GPS 기록</h2><p>개인 러닝 히스토리</p></div><b>›</b></Link></section></main>
}
